# This file created by conda-build 3.20.2
# ------------------------------------------------

package:
    name: curl
    version: 7.71.1
source:
    sha256: 9d52a4d80554f9b0d460ea2be5d7be99897a1a9f681ffafe739169afd6b4f224
    url: http://curl.haxx.se/download/curl-7.71.1.tar.bz2
build:
    noarch: false
    number: '8'
    string: he644dc0_8
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35 h18a2f87_9
        - binutils_linux-64 2.35 heab0d09_28
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 hf34d7eb_28
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35 h769bd43_9
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - krb5 1.17.1 hfafb76e_3
        - libcurl 7.71.1 hcdd3856_8
        - libedit 3.1.20191231 he28a2e2_2
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libssh2 1.9.0 hab1572f_5
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1h h516909a_0
        - tk 8.6.10 hed695b0_0
        - zlib 1.2.11 h516909a_1009
    run:
        - krb5 >=1.17.1,<1.18.0a0
        - libcurl 7.71.1 hcdd3856_8
        - libgcc-ng >=7.5.0
        - libssh2 >=1.9.0,<2.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - curl --help
        - curl https://raw.githubusercontent.com/conda-forge/curl-feedstock/master/LICENSE.txt
about:
    description: 'Curl is an open source command line tool and library for transferring
        data

        with URL syntax. It is used in command lines or scripts to transfer data.

        '
    dev_url: https://github.com/curl/curl
    doc_source_url: https://github.com/curl/curl/tree/master/docs
    doc_url: https://curl.haxx.se/docs/
    home: http://curl.haxx.se/
    license: curl
    license_family: MIT
    license_file: COPYING
    summary: tool and library for transferring data with URL syntax
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
        - xylar
