# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Aug 14 22:11:00 2020
# ------------------------------------------------

package:
    name: wheel
    version: 0.35.1
source:
    sha256: 99a22d87add3f634ff917310a3d87e499f19e663413a52eb9232c447aa646c9f
    url: https://pypi.io/packages/source/w/wheel/wheel-0.35.1.tar.gz
build:
    entry_points:
        - wheel = wheel.cli:main
    noarch: python
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: pyh9f0ad1d_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9f0ad1d_0
        - ld_impl_linux-64 2.34 hc38a660_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_14
        - libgomp 9.3.0 h24d8f2e_14
        - libstdcxx-ng 9.3.0 hdf63c60_14
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - python 3.6.11 h4d41432_2_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py36h9f0ad1d_0
        - sqlite 3.32.3 h4cf870e_1
        - tk 8.6.10 hed695b0_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1007
    run:
        - python
test:
    commands:
        - wheel --help
    imports:
        - wheel
about:
    home: https://github.com/pypa/wheel
    license: MIT
    license_file: LICENSE.txt
    summary: A built-package format for Python.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - ocefpaf
        - pelson
