# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jun 12 11:59:55 2020
# ------------------------------------------------

package:
    name: statsmodels
    version: 0.11.1
source:
    sha256: 5bde3fa0a35a91b45dba7cbc28270b5b649ff1d721c89290883f6e831672d5f0
    url: https://pypi.io/packages/source/s/statsmodels/statsmodels-0.11.1.tar.gz
build:
    number: '2'
    script: /home/conda/feedstock_root/build_artifacts/statsmodels_1591963256838/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py37h8f50634_2
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.34 h53a641e_5
        - binutils_linux-64 2.34 hc952b39_20
        - gcc_impl_linux-64 7.5.0 hd420e75_6
        - gcc_linux-64 7.5.0 h09487f9_20
        - ld_impl_linux-64 2.34 h53a641e_5
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_llvm
        - ca-certificates 2020.4.5.2 hecda079_0
        - certifi 2020.4.5.2 py37hc8dfbb8_0
        - cython 0.29.20 py37h3340039_0
        - ld_impl_linux-64 2.34 h53a641e_5
        - libblas 3.8.0 16_openblas
        - libcblas 3.8.0 16_openblas
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgfortran-ng 7.5.0 hdf63c60_6
        - liblapack 3.8.0 16_openblas
        - libopenblas 0.3.9 h5ec1e0e_0
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - llvm-openmp 10.0.0 hc9558a2_0
        - ncurses 6.1 hf484d3e_1002
        - numpy 1.15.4 py37h8b7e671_1002
        - openssl 1.1.1g h516909a_0
        - pandas 1.0.4 py37h0da4684_0
        - patsy 0.5.1 py_0
        - pip 20.1.1 py_1
        - python 3.7.6 h8356626_5_cpython
        - python-dateutil 2.8.1 py_0
        - python_abi 3.7 1_cp37m
        - pytz 2020.1 pyh9f0ad1d_0
        - readline 8.0 hf8c457e_0
        - scipy 1.4.1 py37ha3d9a3c_3
        - setuptools 47.1.1 py37hc8dfbb8_0
        - six 1.15.0 pyh9f0ad1d_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1006
    run:
        - libgcc-ng >=7.5.0
        - numpy >=1.15.4,<2.0a0
        - pandas >=0.21
        - patsy >=0.5.1
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - scipy >=1.0
test:
    commands:
        - pip check
    imports:
        - statsmodels
    requires:
        - pip
about:
    dev_url: https://github.com/statsmodels/statsmodels
    doc_url: https://www.statsmodels.org/stable/
    home: https://www.statsmodels.org
    license: BSD-3-Clause
    license_file: INSTALL.txt
    summary: Statistical computations and models for use with SciPy
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - croth1
        - ocefpaf
        - tomaugspurger
