# This file created by conda-build 3.20.3
# ------------------------------------------------

package:
    name: libstdcxx-ng
    version: 9.3.0
source:
    path: /home/conda/recipe_root
build:
    binary_relocation: false
    detect_binary_files_with_prefix: false
    ignore_run_exports:
        - __glibc
        - libgcc-ng
    missing_dso_whitelist:
        - '*'
    number: 17
    string: h2ae2ef3_17
requirements:
    host:
        - _sysroot_linux-64_curr_repodata_hack 3 ha9d2b57_10
        - kernel-headers_linux-64 3.10.0 h77966d4_10
        - sysroot_linux-64 2.17 h77966d4_10
test:
    commands:
        - test -f ${PREFIX}/lib/libstdc++.so
about:
    home: https://gcc.gnu.org/
    license: GPL-3.0-only WITH GCC-exception-3.1
    summary: The GNU C++ Runtime Library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - beckermr
        - isuruf
