# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Oct 13 22:12:38 2020
# ------------------------------------------------

package:
    name: pkg-config
    version: 0.29.2
source:
    sha256: 6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591
    url: https://pkg-config.freedesktop.org/releases/pkg-config-0.29.2.tar.gz
build:
    detect_binary_files_with_prefix: true
    number: '1007'
    string: h516909a_1007
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.2 pl526_1
        - binutils_impl_linux-64 2.35 h18a2f87_9
        - binutils_linux-64 2.35 hc3fd857_29
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 he2a3fca_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35 h769bd43_9
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - m4 1.4.18 h516909a_1001
        - make 4.3 h516909a_0
        - perl 5.26.2 h516909a_1006
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
    run:
        - libgcc-ng >=7.5.0
test:
    commands:
        - pkg-config --help
about:
    description: 'pkg-config is a script to make putting together all the build

        flags when compiling/linking a lot easier.

        '
    dev_url: https://cgit.freedesktop.org/pkg-config
    doc_url: https://people.freedesktop.org/~dbn/pkg-config-guide.html
    home: http://www.freedesktop.org/wiki/Software/pkg-config/
    license: GPL-2.0-or-later
    license_file: COPYING
    summary: Interface for querying installed libraries for use during compilation.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mdboom
        - mingwandroid
        - ocefpaf
        - tacaswell
