# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /opt/recipe, last modified Sat Aug 10 19:40:08 2019
# ------------------------------------------------

package:
    name: perl-compress-raw-zlib
    version: '2.087'
source:
    sha256: 8c81c9e1e386b3620ea7aa4c393afe8c80d3587e4fde57b7f83106aea05bee8d
    url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/Compress-Raw-Zlib-2.087.tar.gz
build:
    number: '0'
    string: pl526hc9558a2_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - perl 5.26.2 h516909a_1006
        - perl-extutils-makemaker 7.36 pl526_1
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - perl >=5.26.2,<5.26.3.0a0
test:
    imports:
        - Compress::Raw::Zlib
about:
    home: http://metacpan.org/pod/Compress::Raw::Zlib
    license: perl_5
    summary: Basic utilities for writing tests.
extra:
    copy_test_source_files: true
    final: true
