# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /opt/recipe, last modified Sun Aug 18 14:57:58 2019
# ------------------------------------------------

package:
    name: perl-scalar-list-utils
    version: '1.52'
source:
    sha256: 279d78cef84acae280da4dfb95eff0c9865d1611b1a3b026baddf42d1ba01de4
    url: https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Scalar-List-Utils-1.52.tar.gz
build:
    number: '0'
    string: pl526h516909a_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - perl 5.26.2 h516909a_1006
        - perl-extutils-makemaker 7.36 pl526_1
    run:
        - libgcc-ng >=7.3.0
        - perl >=5.26.2,<5.26.3.0a0
test:
    imports:
        - Scalar::Util
about:
    home: http://metacpan.org/pod/Scalar-List-Utils
    license: perl_5
    summary: Common Scalar and List utility subroutines
extra:
    copy_test_source_files: true
    final: true
