# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug 13 12:13:30 2020
# ------------------------------------------------

package:
    name: libpng
    version: 1.6.37
source:
    patches:
        - 0001-Include-pkg-config-files-in-the-Windows-packages-too.patch
    sha256: daeb2620d829575513e35fecc83f0d3791a620b9b93d800b763542ece9390fb4
    url: http://download.sourceforge.net/libpng/libpng-1.6.37.tar.gz
build:
    number: '2'
    run_exports:
        - libpng >=1.6.37,<1.7.0a0
    string: hed695b0_2
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.2 pl526_1
        - binutils_impl_linux-64 2.34 h2122c62_9
        - binutils_linux-64 2.34 h47ac705_27
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 hf34d7eb_27
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.34 hc38a660_9
        - libgcc-ng 9.3.0 h24d8f2e_14
        - libgomp 9.3.0 h24d8f2e_14
        - libstdcxx-ng 9.3.0 hdf63c60_14
        - libtool 2.4.6 h516909a_1003
        - m4 1.4.18 h14c3975_1001
        - make 4.3 h516909a_0
        - perl 5.26.2 h516909a_1006
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h24d8f2e_14
        - libgomp 9.3.0 h24d8f2e_14
        - zlib 1.2.11 h516909a_1007
    run:
        - libgcc-ng >=7.5.0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libpng.a
        - test -f ${PREFIX}/lib/libpng${SHLIB_EXT}
        - libpng-config --version
about:
    description: 'libpng is the official PNG reference library. It supports almost
        all PNG

        features, is extensible, and has been extensively tested for over 20 years.

        '
    dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/
    doc_url: http://www.libpng.org/pub/png/libpng.html
    home: http://www.libpng.org/pub/png/libpng.html
    license: zlib/libpng
    license_file: LICENSE
    license_url: http://www.libpng.org/pub/png/src/libpng-LICENSE.txt
    summary: PNG reference library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - msarahan
        - ocefpaf
        - pkgw
