# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jan 19 19:06:39 2019
# ------------------------------------------------

package:
    name: prov
    version: 1.5.1
source:
    fn: 1.5.1.tar.gz
    sha256: 527ce639cdd06e09db5f04ca9f1ac855721dafbc015c69933f65dcef71b132d2
    url: https://github.com/trungdong/prov/archive/1.5.1.tar.gz
build:
    noarch: python
    number: '1'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_1
requirements:
    host:
        - ca-certificates 2018.11.29 ha4d7672_0
        - cairo 1.16.0 ha4e643d_1000
        - certifi 2018.11.29 py27_1000
        - decorator 4.3.0 py_0
        - expat 2.2.5 hf484d3e_1002
        - fontconfig 2.13.1 h2176d3f_1000
        - freetype 2.9.1 h94bbf69_1005
        - gettext 0.19.8.1 h9745a5d_1001
        - glib 2.58.2 hf63aee3_1001
        - graphite2 1.3.13 hf484d3e_1000
        - graphviz 2.38.0 hf68f40c_1010
        - harfbuzz 2.3.0 h6824563_1001
        - html5lib 1.0.1 py_0
        - icu 58.2 hf484d3e_1000
        - isodate 0.6.0 py_1
        - jpeg 9c h14c3975_1001
        - keepalive 0.5 py_1
        - libffi 3.2.1 hf484d3e_1005
        - libgcc-ng 7.3.0 hdf63c60_0
        - libiconv 1.15 h14c3975_1004
        - libpng 1.6.36 h84994c4_1000
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - libtiff 4.0.10 h648cc4a_1001
        - libtool 2.4.6 h14c3975_1002
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.8 h143f9aa_1005
        - libxslt 1.1.32 h4785a14_1002
        - lxml 4.3.0 py27h23eabaa_1000
        - ncurses 6.1 hf484d3e_1002
        - networkx 2.2 py_1
        - openssl 1.0.2p h14c3975_1002
        - pango 1.40.14 h4ea9474_1004
        - pcre 8.41 hf484d3e_1003
        - pip 18.1 py27_1000
        - pixman 0.34.0 h14c3975_1003
        - pthread-stubs 0.4 h14c3975_1001
        - pydotplus 2.0.2 py_2
        - pyparsing 2.3.1 py_0
        - python 2.7.15 h938d71a_1006
        - python-dateutil 2.7.5 py_0
        - rdflib 4.2.2 py27_1000
        - readline 7.0 hf8c457e_1001
        - setuptools 40.6.3 py27_0
        - six 1.12.0 py27_1000
        - sparqlwrapper 1.8.2 py27_1000
        - sqlite 3.26.0 h67949de_1000
        - tk 8.6.9 h84994c4_1000
        - webencodings 0.5.1 py_1
        - wheel 0.32.3 py27_0
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.9 h14c3975_1004
        - xorg-libsm 1.2.3 h4937e3b_1000
        - xorg-libx11 1.6.6 h14c3975_1000
        - xorg-libxau 1.0.8 h14c3975_1006
        - xorg-libxdmcp 1.1.2 h14c3975_1007
        - xorg-libxext 1.3.3 h14c3975_1004
        - xorg-libxpm 3.5.12 h14c3975_1002
        - xorg-libxrender 0.9.10 h14c3975_1002
        - xorg-libxt 1.1.5 h14c3975_1002
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - lxml >=3.3.5
        - networkx >=1.10
        - pydotplus >=2.0.2
        - python
        - python-dateutil >=2.2
        - rdflib >=4.2.1
        - six >=1.9.0
test:
    imports:
        - prov
        - prov.serializers
        - prov.tests
about:
    home: https://github.com/trungdong/prov
    license: MIT
    summary: A library for W3C Provenance Data Model supporting PROV-JSON and PROV-XML
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chrisfilo
        - satra
        - trungdong
