# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Nov 17 02:38:37 2019
# ------------------------------------------------

package:
    name: pyasn1
    version: 0.4.8
source:
    sha256: aef77c9fb94a3ac588e87841208bdec464471d9871bd5050a287cc9a475cd0ba
    url: https://pypi.org/packages/source/p/pyasn1/pyasn1-0.4.8.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/pyasn1_1573958397129/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.9.11 hecc5488_0
        - certifi 2019.9.11 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 19.3.1 py27_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 41.6.0 py27_1
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.9 hed695b0_1003
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h516909a_1006
    run:
        - python
test:
    imports:
        - pyasn1
        - pyasn1.codec
        - pyasn1.codec.ber
        - pyasn1.codec.cer
        - pyasn1.codec.der
        - pyasn1.compat
        - pyasn1.type
about:
    description: 'Pure-Python implementation of ASN.1 types and DER/BER/CER codecs
        (X.208)

        '
    dev_url: https://github.com/etingof/pyasn1
    doc_source_url: https://github.com/etingof/pyasn1/blob/master/doc/source/contents.rst
    doc_url: http://pyasn1.sourceforge.net/
    home: https://github.com/etingof/pyasn1
    license: BSD 2-Clause
    license_family: BSD
    license_file: LICENSE.rst
    summary: ASN.1 types and codecs
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
