# This file created by conda-build 3.18.7
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jul 16 17:04:03 2019
# ------------------------------------------------

package:
    name: biopython
    version: '1.74'
source:
    fn: biopython-1.74.tar.gz
    sha256: 25152c1be2c9205bf80901fc49adf2c2efff49f0dddbcf6e6b2ce31dfa6590c0
    url: https://pypi.io/packages/source/b/biopython/biopython-1.74.tar.gz
build:
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/biopython_1563296733626/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37h516909a_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py37_1
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pip 19.1.1 py37_0
        - python 3.7.3 h33d41f4_1
        - readline 8.0 hf8c457e_0
        - setuptools 41.0.1 py37_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - wheel 0.33.4 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - libgcc-ng >=7.3.0
        - numpy
        - python >=3.7,<3.8.0a0
test:
    imports:
        - Bio
        - Bio.Affy
        - Bio.Align
        - Bio.Align.Applications
        - Bio.AlignIO
        - Bio.Alphabet
        - Bio.Application
        - Bio.Blast
        - Bio.CAPS
        - Bio.Cluster
        - Bio.Compass
        - Bio.Crystal
        - Bio.Data
        - Bio.Emboss
        - Bio.Entrez
        - Bio.ExPASy
        - Bio.FSSP
        - Bio.GenBank
        - Bio.Geo
        - Bio.HMM
        - Bio.KDTree
        - Bio.KEGG
        - Bio.KEGG.Compound
        - Bio.KEGG.Enzyme
        - Bio.KEGG.KGML
        - Bio.KEGG.Map
        - Bio.Medline
        - Bio.NMR
        - Bio.Nexus
        - Bio.PDB
        - Bio.PDB.QCPSuperimposer
        - Bio.Pathway
        - Bio.Pathway.Rep
        - Bio.Phylo
        - Bio.Phylo.Applications
        - Bio.Phylo.PAML
        - Bio.PopGen
        - Bio.PopGen.GenePop
        - Bio.Restriction
        - Bio.SCOP
        - Bio.SVDSuperimposer
        - Bio.SearchIO
        - Bio.SearchIO.BlastIO
        - Bio.SearchIO.ExonerateIO
        - Bio.SearchIO.HmmerIO
        - Bio.SearchIO._model
        - Bio.SeqIO
        - Bio.SeqUtils
        - Bio.Sequencing
        - Bio.Sequencing.Applications
        - Bio.Statistics
        - Bio.SubsMat
        - Bio.SwissProt
        - Bio.TogoWS
        - Bio.UniGene
        - Bio.UniProt
        - Bio.Wise
        - Bio._py3k
        - Bio.codonalign
        - Bio.cpairwise2
        - Bio.motifs
        - Bio.motifs.applications
        - Bio.motifs.jaspar
        - Bio.phenotype
        - Bio.trie
        - BioSQL
about:
    description: 'Biopython is a collection of freely available Python tools for

        computational molecular biology

        '
    dev_url: https://github.com/biopython/biopython
    doc_url: http://biopython.org
    home: http://biopython.org
    license: Biopython License Agreement
    license_file: LICENSE.rst
    summary: Collection of freely available tools for computational molecular biology
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - peterjc
        - souravsingh
