# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Oct 10 00:18:45 2020
# ------------------------------------------------

package:
    name: keepalive
    version: '0.5'
source:
    -   sha256: 3c6b96f9062a5a76022f0c9d41e9ef5552d80b1cadd4fccc1bf8f183ba1d1ec1
        url: https://pypi.io/packages/source/k/keepalive/keepalive-0.5.tar.gz
    -   sha256: 7c6699c75f87b52bdc542db26d6b1b92892577cda46e20eceb79e2790a1c291b
        url: https://raw.githubusercontent.com/wikier/keepalive/0.5/LICENSE
build:
    number: '4'
    script: /home/conda/feedstock_root/build_artifacts/keepalive_1602289188236/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install --no-deps -vv .
    string: py37hc8dfbb8_4
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py37he5f6b98_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.7.8 h6f2ec95_1_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py37he5f6b98_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
test:
    imports:
        - keepalive
        - keepalive.keepalive
about:
    dev_url: https://github.com/wikier/keepalive
    home: https://github.com/wikier/keepalive
    license: LGPL-2.1-or-later
    license_file: LICENSE
    summary: An HTTP handler for urllib that supports HTTP 1.1 and keepalive in both
        Python 2.x and 3.x versions.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
        - satra
