# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jun  2 04:21:41 2020
# ------------------------------------------------

package:
    name: gdk-pixbuf
    version: 2.38.2
source:
    patches:
        - 0001-changed-perl-script-to-use-env.patch
        - meson-rpaths-common.patch
        - meson-rpaths-non-macos.patch
    sha256: 73fa651ec0d89d73dd3070b129ce2203a66171dfc0bd2caa3570a9c93d2d0781
    url: http://ftp.gnome.org/pub/gnome/sources/gdk-pixbuf/2.38/gdk-pixbuf-2.38.2.tar.xz
build:
    number: '4'
    run_exports:
        - gdk-pixbuf >=2.38.2,<3.0a0
    string: h3f25603_4
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.34 h53a641e_4
        - binutils_linux-64 2.34 hc952b39_20
        - ca-certificates 2020.4.5.1 hecc5488_0
        - gcc_impl_linux-64 7.5.0 hd420e75_6
        - gcc_linux-64 7.5.0 h09487f9_20
        - ld_impl_linux-64 2.34 h53a641e_4
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - meson 0.53.2 py_0
        - ncurses 6.1 hf484d3e_1002
        - ninja 1.10.0 hc9558a2_0
        - openssl 1.1.1g h516909a_0
        - pkg-config 0.29.2 h516909a_1006
        - python 3.8.3 cpython_he5300dc_0
        - readline 8.0 hf8c457e_0
        - sqlite 3.30.1 hcee41ef_0
        - sysroot_linux-64 2.12 h3a0023d_5
        - tk 8.6.10 hed695b0_0
        - xz 5.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1006
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2020.4.5.1 hecc5488_0
        - cairo 1.16.0 h3fc0475_1004
        - fontconfig 2.13.1 h1056068_1002
        - freetype 2.10.2 he06d7ca_0
        - gettext 0.19.8.1 hc5be6a0_1002
        - glib 2.58.3 py38h73cb85d_1004
        - gobject-introspection 1.64.1 py38h03d966d_1
        - icu 67.1 he1b5a44_0
        - jpeg 9d h516909a_0
        - ld_impl_linux-64 2.34 h53a641e_4
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libiconv 1.15 h516909a_1006
        - libpng 1.6.37 hed695b0_1
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - libtiff 4.1.0 hc7e4089_6
        - libuuid 2.32.1 h14c3975_1000
        - libwebp-base 1.1.0 h516909a_3
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.10 h72b56ed_1
        - lz4-c 1.9.2 he1b5a44_1
        - make 4.3 h516909a_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1g h516909a_0
        - pcre 8.44 he1b5a44_0
        - pixman 0.38.0 h516909a_1003
        - pthread-stubs 0.4 h14c3975_1001
        - python 3.8.3 cpython_he5300dc_0
        - python_abi 3.8 1_cp38
        - readline 8.0 hf8c457e_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.10 h516909a_0
        - xorg-libsm 1.2.3 h84519dc_1000
        - xorg-libx11 1.6.9 h516909a_0
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-libxext 1.3.4 h516909a_0
        - xorg-libxrender 0.9.10 h516909a_1002
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1006
        - zstd 1.4.4 h6597ccf_3
    run:
        - glib >=2.58.3,<3.0a0
        - gobject-introspection
        - jpeg >=9d,<10a
        - jpeg >=9d,<10a
        - libgcc-ng >=7.5.0
        - libpng >=1.6.37,<1.7.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libtiff >=4.1.0,<5.0a0
        - libtiff >=4.1.0,<5.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - gdk-pixbuf-csource --version
        - gdk-pixbuf-query-loaders
        - gdk-pixbuf-pixdata --help
        - test -f $PREFIX/lib/libgdk_pixbuf-2.0${SHLIB_EXT}
        - test -f `pkg-config --variable=libdir --dont-define-prefix gdk-pixbuf-2.0`/libgdk_pixbuf-2.0${SHLIB_EXT}
    requires:
        - pkg-config
about:
    home: https://developer.gnome.org/gdk-pixbuf/
    license: LGPL-2.1-or-later
    license_family: LGPL
    license_file: COPYING
    summary: GdkPixbuf is a library for image loading and manipulation.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - notestaff
        - pkgw
