# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Nov 11 20:52:01 2019
# ------------------------------------------------

package:
    name: seaborn
    version: 0.9.0
source:
    sha256: 76c83f794ca320fb6b23a7c6192d5e185a5fcf4758966a0c0a54baee46d41e2f
    url: https://pypi.io/packages/source/s/seaborn/seaborn-0.9.0.tar.gz
build:
    noarch: python
    number: '2'
    script: /home/conda/feedstock_root/build_artifacts/seaborn_1573505605838/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps -vv
    string: py_2
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.9.11 hecc5488_0
        - certifi 2019.9.11 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 19.3.1 py27_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 41.6.0 py27_1
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.9 hed695b0_1003
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h516909a_1006
    run:
        - matplotlib-base
        - numpy >=1.9.3
        - pandas >=0.14.0
        - python
        - scipy >=0.15.2
        - statsmodels >=0.5.0
test:
    imports:
        - seaborn
about:
    description: 'Seaborn is a Python visualization library based on matplotlib. It

        provides a high-level interface for drawing attractive statistical graphics.

        '
    dev_url: https://github.com/mwaskom/seaborn
    doc_url: https://seaborn.pydata.org
    home: https://seaborn.pydata.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Statistical data visualization
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - croth1
        - msarahan
        - r-jain1
