# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 25 09:40:26 2020
# ------------------------------------------------

package:
    name: c-ares
    version: 1.16.1
source:
    sha256: d08312d0ecc3bd48eee0a4cc0d2137c9f194e0a28de2028928c0f6cae85f86ce
    url: https://c-ares.haxx.se/download/c-ares-1.16.1.tar.gz
build:
    number: '3'
    run_exports:
        - c-ares >=1.16.1,<2.0a0
    string: h516909a_3
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.34 h2122c62_9
        - binutils_linux-64 2.34 h47ac705_27
        - ca-certificates 2020.6.20 hecda079_0
        - cmake-no-system 3.16.4 he1b5a44_0
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 hf34d7eb_27
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.34 hc38a660_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - ncurses 6.2 he1b5a44_1
        - ninja 1.10.1 hbf85e49_0
        - openssl 1.1.1g h516909a_1
        - python 3.8.5 h1103e12_5_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 he28a2e2_2
        - sqlite 3.33.0 h4cf870e_0
        - sysroot_linux-64 2.12 h77966d4_13
        - tk 8.6.10 hed695b0_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1007
    run:
        - libgcc-ng >=7.5.0
    run_constraint:
        - c-ares-static <0a0
about:
    home: https://c-ares.haxx.se/
    license: MIT
    license_family: MIT
    license_file: LICENSE.md
    summary: This is c-ares, an asynchronous resolver library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - wesm
        - xhochy
