# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Mar 26 08:51:34 2019
# ------------------------------------------------

package:
    name: jupyter
    version: 1.0.0
build:
    noarch: python
    number: '2'
    string: py_2
requirements:
    host:
        - ca-certificates 2019.3.9 hecc5488_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - python 2.7.15 h721da81_1008
        - readline 7.0 hf8c457e_1001
        - sqlite 3.26.0 h67949de_1001
        - tk 8.6.9 h84994c4_1000
        - zlib 1.2.11 h14c3975_1004
    run:
        - ipykernel
        - ipywidgets
        - jupyter_console
        - nbconvert
        - notebook
        - python
        - qtconsole
test:
    commands:
        - jupyter --help
        - jupyter nbextension list
about:
    dev_url: https://github.com/jupyter/jupyter
    home: http://jupyter.org
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Jupyter metapackage. Install all the Jupyter components in one go.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - ocefpaf
        - xylar
