# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Feb 11 11:50:25 2019
# ------------------------------------------------

package:
    name: xmltodict
    version: 0.12.0
source:
    sha256: 50d8c638ed7ecb88d90561beedbf720c9b4e851a9fa6c47ebd64e99d166d8a21
    url: https://pypi.io/packages/source/x/xmltodict/xmltodict-0.12.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/xmltodict_1549885914050/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - ca-certificates 2018.11.29 ha4d7672_0
        - certifi 2018.11.29 py27_1000
        - libffi 3.2.1 hf484d3e_1005
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.0.2p h14c3975_1002
        - pip 19.0.2 py27_0
        - python 2.7.15 h938d71a_1006
        - readline 7.0 hf8c457e_1001
        - setuptools 40.8.0 py27_0
        - sqlite 3.26.0 h67949de_1000
        - tk 8.6.9 h84994c4_1000
        - wheel 0.32.3 py27_0
        - zlib 1.2.11 h14c3975_1004
    run:
        - python
test:
    imports:
        - xmltodict
about:
    dev_url: https://github.com/martinblech/xmltodict
    home: https://github.com/martinblech/xmltodict
    license: MIT
    license_file: LICENSE
    summary: Makes working with XML feel like you are working with JSON
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - synapticarbors
