CI: azure
c_compiler: gcc
c_compiler_version: '7'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: condaforge/linux-anvil-comp7
extend_keys:
- ignore_version
- extend_keys
- ignore_build_only_deps
- pin_run_as_build
fontconfig: '2.13'
fortran_compiler: gfortran
freetype: 2.9.1
glib: '2.58'
icu: '64.2'
ignore_build_only_deps:
- numpy
- python
libpng: '1.6'
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  fontconfig:
    max_pin: x
  freetype:
    max_pin: x
  icu:
    max_pin: x
  libpng:
    max_pin: x.x
  pixman:
    max_pin: x.x
  xz:
    max_pin: x.x
  zlib:
    max_pin: x.x
pixman: '0.38'
python: '3.7'
r_base: '3.5'
target_platform: linux-64
xz: '5.2'
zlib: '1.2'
