# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Oct  6 13:04:40 2020
# ------------------------------------------------

package:
    name: librsvg
    version: 2.50.1
source:
    fn: librsvg-2.50.1.tar.xz
    patches:
        - add_rust_lto.patch
    sha256: 9bd9799322e06cf5db19b9f7afb728edac6efcf0110baafc44f0f96f45df9a09
    url: http://ftp.gnome.org/pub/gnome/sources/librsvg/2.50/librsvg-2.50.1.tar.xz
build:
    number: '0'
    run_exports:
        - librsvg >=2.50.1,<3.0a0
    string: h33a7fed_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35 h18a2f87_9
        - binutils_linux-64 2.35 hc3fd857_29
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 he2a3fca_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35 h769bd43_9
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - make 4.3 h516909a_0
        - pkg-config 0.29.2 h516909a_1006
        - rust 1.46.0 hd18ef5c_1
        - rust-std-x86_64-unknown-linux-gnu 1.46.0 hdfb2d09_1
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - cairo 1.16.0 h3fc0475_1005
        - fontconfig 2.13.1 h1056068_1002
        - freetype 2.10.2 he06d7ca_0
        - fribidi 1.0.10 h516909a_0
        - gdk-pixbuf 2.36.12 h3f25603_1005
        - gettext 0.19.8.1 hc5be6a0_1002
        - glib 2.58.3 py38h73cb85d_1004
        - gobject-introspection 1.66.1 py38h03d966d_0
        - graphite2 1.3.13 he1b5a44_1001
        - harfbuzz 2.7.2 hee91db6_0
        - icu 67.1 he1b5a44_0
        - jpeg 9d h516909a_0
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libiconv 1.16 h516909a_0
        - libpng 1.6.37 hed695b0_2
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - libtiff 4.1.0 hc7e4089_6
        - libuuid 2.32.1 h14c3975_1000
        - libwebp-base 1.1.0 h516909a_3
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.10 h68273f3_2
        - lz4-c 1.9.2 he1b5a44_3
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1h h516909a_0
        - pango 1.42.4 h7062337_4
        - pcre 8.44 he1b5a44_0
        - pixman 0.38.0 h516909a_1003
        - pthread-stubs 0.4 h14c3975_1001
        - python 3.8.5 h1103e12_9_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 he28a2e2_2
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.10 h516909a_0
        - xorg-libsm 1.2.3 h84519dc_1000
        - xorg-libx11 1.6.12 h516909a_0
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-libxext 1.3.4 h516909a_0
        - xorg-libxrender 0.9.10 h516909a_1002
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
        - zstd 1.4.5 h6597ccf_2
    run:
        - cairo >=1.16.0,<1.17.0a0
        - cairo >=1.16.0,<1.17.0a0
        - gdk-pixbuf >=2.36.12,<3.0a0
        - glib >=2.58.3,<3.0a0
        - libgcc-ng >=7.5.0
        - libxml2 >=2.9.10,<2.10.0a0
        - libxml2 >=2.9.10,<2.10.0a0
        - pango >=1.42.4,<1.43.0a0
test:
    commands:
        - rsvg-convert --version
        - test -f $PREFIX/lib/librsvg-2${SHLIB_EXT}
        - test -f `pkg-config --variable=libdir --dont-define-prefix librsvg-2.0`/librsvg-2${SHLIB_EXT}
        - test -f $PREFIX/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
        - test -f $PREFIX/include/librsvg-2.0/librsvg/librsvg-features.h
        - test -f $PREFIX/include/librsvg-2.0/librsvg/rsvg-cairo.h
        - test -f $PREFIX/include/librsvg-2.0/librsvg/rsvg.h
    requires:
        - pkg-config
about:
    home: https://wiki.gnome.org/Projects/LibRsvg
    license: LGPL-2.1-or-later
    license_file: COPYING.LIB
    summary: librsvg is a library to render SVG files using cairo.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jenzopr
        - pkgw
