# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Sep 27 12:49:16 2020
# ------------------------------------------------

package:
    name: libdb
    version: 6.2.32
source:
    sha256: a9c5e2b004a5777aa03510cfe5cd766a4a3b777713406b02809c17c8e0e7a8fb
    url: http://download.oracle.com/berkeley-db/db-6.2.32.tar.gz
build:
    number: '0'
    run_exports:
        - libdb >=6.2.32,<6.3.0a0
    string: he1b5a44_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35 h18a2f87_9
        - binutils_linux-64 2.35 heab0d09_28
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 hf34d7eb_28
        - gxx_impl_linux-64 7.5.0 h64c220c_13
        - gxx_linux-64 7.5.0 ha781d05_28
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35 h769bd43_9
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - make 4.3 h516909a_0
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
    run:
        - libgcc-ng >=7.5.0
        - libstdcxx-ng >=7.5.0
about:
    home: http://www.oracle.com/technology/software/products/berkeley-db/index.html
    license: AGPL-3.0-only
    license_file: LICENSE
    summary: The Berkeley DB embedded database system.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mingwandroid
        - msarahan
        - ocefpaf
        - scopatz
