# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /opt/recipe, last modified Sat May 11 04:31:19 2019
# ------------------------------------------------

package:
    name: perl-net-ssleay
    version: '1.88'
source:
    sha256: 02f64e2d7722dc83d831bef4099d17b5f4f2f07f87b786c806b67276979f7273
    url: https://github.com/radiator-software/p5-net-ssleay/archive/1.88.tar.gz
build:
    number: '0'
    string: pl526h90d6eec_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    host:
        - ca-certificates 2019.3.9 hecc5488_0
        - libgcc-ng 8.2.0 hdf63c60_1
        - openssl 1.1.1a h14c3975_1001
        - perl 5.26.2 h516909a_1006
        - perl-extutils-makemaker 7.36 pl526_1
        - perl-mime-base64 3.15 pl526_1
        - perl-xsloader 0.24 pl526_0
        - zlib 1.2.11 h14c3975_1004
    run:
        - libgcc-ng >=7.3.0
        - openssl >=1.1.1a,<1.1.2a
        - openssl >=1.1.1a,<1.1.2a
        - perl >=5.26.2,<5.26.3.0a0
        - perl-mime-base64
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    imports:
        - Net::SSLeay
about:
    home: http://metacpan.org/pod/Net::SSLeay
    license: perl_5
    summary: Perl extension for using OpenSSL
extra:
    copy_test_source_files: true
    final: true
