# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Oct 14 13:39:04 2020
# ------------------------------------------------

package:
    name: ipykernel
    version: 5.3.4
source:
    sha256: 9b2652af1607986a1b231c62302d070bc0534f564c393a5d9d130db9abbbe89d
    url: https://pypi.io/packages/source/i/ipykernel/ipykernel-5.3.4.tar.gz
build:
    number: '1'
    script:
        - /home/conda/feedstock_root/build_artifacts/ipykernel_1602682802500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
            setup.py bdist_wheel
        - cd dist
        - /home/conda/feedstock_root/build_artifacts/ipykernel_1602682802500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
            -m pip install ipykernel-5.3.4-py3-none-any.whl --no-deps -vv
        - /home/conda/feedstock_root/build_artifacts/ipykernel_1602682802500/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
            -m ipykernel install --sys-prefix
    string: py37hc6149b9_1
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - backcall 0.2.0 pyh9f0ad1d_0
        - backports 1.0 py_2
        - backports.functools_lru_cache 1.6.1 py_0
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py37he5f6b98_2
        - decorator 4.4.2 py_0
        - ipython 7.18.1 py37hc6149b9_1
        - ipython_genutils 0.2.0 py_1
        - jedi 0.17.2 py37hc8dfbb8_1
        - jupyter_client 6.1.7 py_0
        - jupyter_core 4.6.3 py37hc8dfbb8_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libsodium 1.0.18 h516909a_1
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - parso 0.7.1 pyh9f0ad1d_0
        - pexpect 4.8.0 pyh9f0ad1d_2
        - pickleshare 0.7.5 py_1003
        - pip 20.2.3 py_0
        - prompt-toolkit 3.0.8 py_0
        - ptyprocess 0.6.0 py_1001
        - pygments 2.7.1 py_0
        - python 3.7.8 h6f2ec95_1_cpython
        - python-dateutil 2.8.1 py_0
        - python_abi 3.7 1_cp37m
        - pyzmq 19.0.2 py37hac76be4_2
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py37he5f6b98_2
        - six 1.15.0 pyh9f0ad1d_0
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - tornado 6.0.4 py37h8f50634_2
        - traitlets 5.0.4 py_1
        - wcwidth 0.2.5 pyh9f0ad1d_2
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zeromq 4.3.3 he1b5a44_2
        - zlib 1.2.11 h516909a_1010
    run:
        - ipython >=5.0
        - jupyter_client
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - tornado >=4.2
        - traitlets >=4.1
test:
    commands:
        - jupyter kernelspec list
    imports:
        - ipykernel
    requires:
        - curio
        - flaky
        - ipython
        - nose
        - numpy
        - pytest !=5.3.4
about:
    description: 'A powerful interactive Python shell and a Jupyter kernel to work
        with

        Python code in Jupyter notebooks and other interactive frontends.

        '
    dev_url: https://github.com/ipython/ipykernel
    doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst
    doc_url: https://ipython.readthedocs.io
    home: https://ipython.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING.md
    summary: IPython Kernel for Jupyter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Carreau
        - blink1073
        - bollwyvl
        - jakirkham
        - minrk
        - ocefpaf
        - pelson
