# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Oct 12 23:48:38 2020
# ------------------------------------------------

package:
    name: argon2-cffi
    version: 20.1.0
source:
    fn: argon2-cffi-20.1.0.tar.gz
    sha256: d8029b2d3e4b4cea770e9e5a0104dd8fa185c1724a0f01528ae4826a6d25f97d
    url: https://pypi.io/packages/source/a/argon2-cffi/argon2-cffi-20.1.0.tar.gz
build:
    number: '2'
    script:
        - ln -sf $RANLIB $BUILD_PREFIX/bin/ranlib
        - /home/conda/feedstock_root/build_artifacts/argon2-cffi_1602546578258/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
            -m pip install . -vv
    string: py37h8f50634_2
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35 h18a2f87_9
        - binutils_linux-64 2.35 hc3fd857_29
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 he2a3fca_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35 h769bd43_9
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py37he5f6b98_2
        - cffi 1.14.3 py37h00ebd2e_1
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - pycparser 2.20 pyh9f0ad1d_2
        - python 3.7.8 h6f2ec95_1_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py37he5f6b98_2
        - six 1.15.0 pyh9f0ad1d_0
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - cffi >=1.0.0
        - libgcc-ng >=7.5.0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - six
    run_constrained:
        - argon2_cffi ==999
test:
    imports:
        - argon2
about:
    description: 'Argon2 won the Password Hashing Competition and argon2_cffi is the
        simplest

        way to use it in Python and PyPy

        '
    dev_url: https://github.com/hynek/argon2_cffi/
    doc_url: https://argon2-cffi.readthedocs.io/en/stable/
    home: https://argon2-cffi.readthedocs.org/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: The secure Argon2 password hashing algorithm.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - stuertz
