CI: azure
bzip2: '1'
c_compiler: gcc
c_compiler_version: '7'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '7'
docker_image: condaforge/linux-anvil-comp7
extend_keys:
- ignore_version
- pin_run_as_build
- extend_keys
- ignore_build_only_deps
fftw: '3'
fontconfig: '2.13'
fortran_compiler: gfortran
freetype: 2.9.1
giflib: '5.2'
graphviz: '2.40'
ignore_build_only_deps:
- python
- numpy
jpeg: '9'
libpng: '1.6'
librsvg: '2'
libtiff: 4.1.0
libwebp: '1.0'
libxml2: '2.9'
lua: '5'
numpy: '1.11'
openjpeg: '2.3'
pango: '1.42'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  bzip2:
    max_pin: x
  fftw:
    max_pin: x
  fontconfig:
    max_pin: x
  freetype:
    max_pin: x
  graphviz:
    max_pin: x
  jpeg:
    max_pin: x
  libpng:
    max_pin: x.x
  librsvg:
    max_pin: x
  libtiff:
    max_pin: x
  libwebp:
    max_pin: x.x
  libxml2:
    max_pin: x.x
  openjpeg:
    max_pin: x.x
  pango:
    max_pin: x.x
  perl:
    max_pin: x.x.x
  xz:
    max_pin: x.x
  zlib:
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
xz: '5.2'
zlib: '1.2'
