# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Mar  1 10:43:30 2020
# ------------------------------------------------

package:
    name: imagemagick
    version: 7.0.9_27
source:
    sha256: aeea7768bf330d87efa80fa89f03c5acc2382eae32d1d871acb813e5b116395a
    url: https://github.com/ImageMagick/ImageMagick/archive/7.0.9-27.tar.gz
build:
    number: '0'
    string: pl526ha9fe49d_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.33.1 h53a641e_8
        - binutils_linux-64 2.33.1 h9595d00_16
        - gcc_impl_linux-64 7.3.0 hd420e75_5
        - gcc_linux-64 7.3.0 h553295d_16
        - gxx_impl_linux-64 7.3.0 hdf63c60_5
        - gxx_linux-64 7.3.0 h553295d_16
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - bzip2 1.0.8 h516909a_2
        - ca-certificates 2019.11.28 hecc5488_0
        - cairo 1.16.0 hfb77d84_1002
        - expat 2.2.9 he1b5a44_2
        - fftw 3.3.8 nompi_h7f3a6c3_1110
        - font-ttf-dejavu-sans-mono 2.37 hab24e00_0
        - font-ttf-inconsolata 2.001 hab24e00_0
        - font-ttf-source-code-pro 2.030 hab24e00_0
        - font-ttf-ubuntu 0.83 hab24e00_0
        - fontconfig 2.13.1 h86ecdb6_1001
        - fonts-conda-forge 1 0
        - freetype 2.9.1 he983fc9_1006
        - fribidi 1.0.5 h516909a_1002
        - gdk-pixbuf 2.38.2 h3f25603_0
        - gettext 0.19.8.1 hc5be6a0_1002
        - ghostscript 9.22 hf484d3e_1001
        - giflib 5.2.1 h516909a_2
        - glib 2.58.3 py38h6f030ca_1002
        - gobject-introspection 1.58.2 py38h5503ade_1002
        - graphite2 1.3.13 hf484d3e_1000
        - graphviz 2.40.1 h0511662_2
        - harfbuzz 2.4.0 h9f30f68_3
        - icu 64.2 he1b5a44_1
        - jbig 2.1 h14c3975_2001
        - jpeg 9c h14c3975_1001
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libcroco 0.6.13 h8d621e5_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgfortran-ng 7.3.0 hdf63c60_5
        - libgomp 9.2.0 h24d8f2e_2
        - libiconv 1.15 h516909a_1005
        - libpng 1.6.37 hed695b0_0
        - librsvg 2.46.4 h33a7fed_0
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - libtiff 4.1.0 hc3755c2_3
        - libtool 2.4.6 h14c3975_1002
        - libuuid 2.32.1 h14c3975_1000
        - libwebp 1.0.2 h56121f0_5
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.10 hee79883_0
        - lz4-c 1.8.3 he1b5a44_1001
        - ncurses 6.1 hf484d3e_1002
        - openjpeg 2.3.1 h981e76c_3
        - openssl 1.1.1d h516909a_0
        - pango 1.42.4 ha030887_1
        - pcre 8.44 he1b5a44_0
        - perl 5.26.2 h516909a_1006
        - pixman 0.38.0 h516909a_1003
        - pkg-config 0.29.2 h516909a_1006
        - pthread-stubs 0.4 h14c3975_1001
        - python 3.8.2 h9d8adfe_1_cpython
        - readline 8.0 hf8c457e_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.10 h516909a_0
        - xorg-libsm 1.2.3 h84519dc_1000
        - xorg-libx11 1.6.9 h516909a_0
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-libxext 1.3.4 h516909a_0
        - xorg-libxpm 3.5.13 h516909a_0
        - xorg-libxrender 0.9.10 h516909a_1002
        - xorg-libxt 1.1.5 h516909a_1003
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
        - zstd 1.4.4 h3b9ef0a_1
    run:
        - bzip2 >=1.0.8,<2.0a0
        - bzip2 >=1.0.8,<2.0a0
        - fftw >=3.3.8,<4.0a0
        - fontconfig >=2.13.1,<3.0a0
        - fontconfig >=2.13.1,<3.0a0
        - fonts-conda-forge
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - ghostscript
        - giflib >=5.2.1,<5.3.0a0
        - graphviz >=2.40.1,<3.0a0
        - jbig
        - jpeg >=9c,<10a
        - jpeg >=9c,<10a
        - libgcc-ng >=7.3.0
        - libpng >=1.6.37,<1.7.0a0
        - libpng >=1.6.37,<1.7.0a0
        - librsvg >=2.46.4,<3.0a0
        - librsvg >=2.46.4,<3.0a0
        - libstdcxx-ng >=7.3.0
        - libtiff >=4.1.0,<5.0a0
        - libtiff >=4.1.0,<5.0a0
        - libwebp >=1.0.2,<1.1.0a0
        - libwebp >=1.0.2,<1.1.0a0
        - libxml2 >=2.9.10,<2.10.0a0
        - libxml2 >=2.9.10,<2.10.0a0
        - openjpeg >=2.3.1,<2.4.0a0
        - openjpeg >=2.3.1,<2.4.0a0
        - pango >=1.42.4,<1.43.0a0
        - perl >=5.26.2,<5.26.3.0a0
        - pkg-config
        - xorg-libx11
        - xorg-libxext
        - xorg-libxrender
        - xorg-libxt
        - xz >=5.2.4,<5.3.0a0
        - xz >=5.2.4,<5.3.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - convert -version
        - Magick++-config --cflags
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: http://www.imagemagick.org/
    license: ImageMagick
    license_file: LICENSE
    summary: Software suite to create, edit, compose, or convert bitmap images.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - halldc
        - ocefpaf
