# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /opt/recipe, last modified Mon Apr 22 04:34:29 2019
# ------------------------------------------------

package:
    name: perl-db-file
    version: '1.852'
source:
    sha256: 3ab7957523b6da39c55cb2ec4e677d88aa4034fd0b2f40788781a58e7d078391
    url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/DB_File-1.852.tar.gz
build:
    number: '0'
    string: pl526h14c3975_0
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_6
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_6
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    host:
        - libdb 6.1.26 hf484d3e_2000
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - perl 5.26.2 h516909a_1006
    run:
        - libdb
        - libgcc-ng >=7.3.0
        - perl >=5.26.2,<5.26.3.0a0
test:
    imports:
        - DB_File
about:
    home: https://metacpan.org/pod/Set::IntervalTree
    license: perl_5
    summary: Perl5 access to Berkeley DB version 1.x.
extra:
    copy_test_source_files: true
    final: true
