# This file created by conda-build 3.16.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Oct  6 23:51:52 2018
# ------------------------------------------------

package:
    name: rdflib
    version: 4.2.2
source:
    fn: rdflib-4.2.2.tar.gz
    sha256: da1df14552555c5c7715d8ce71c08f404c988c58a1ecd38552d0da4fc261280d
    url: https://pypi.io/packages/source/r/rdflib/rdflib-4.2.2.tar.gz
build:
    entry_points:
        - csv2rdf = rdflib.tools.csv2rdf:main
        - rdf2dot = rdflib.tools.rdf2dot:main
        - rdfgraphisomorphism = rdflib.tools.graphisomorphism:main
        - rdfpipe = rdflib.tools.rdfpipe:main
        - rdfs2dot = rdflib.tools.rdfs2dot:main
    number: '1000'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py37_1000
requirements:
    build:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.8.24 ha4d7672_0
        - certifi 2018.8.24 py37_1001
        - isodate 0.6.0 py_1
        - libffi 3.2.1 hfc679d8_5
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2p h470a237_0
        - pyparsing 2.2.2 py_0
        - python 3.7.0 h5001a0f_4
        - readline 7.0 haf1bffa_1
        - setuptools 40.4.3 py37_0
        - six 1.11.0 py37_1001
        - sqlite 3.25.2 hb1c47c0_0
        - tk 8.6.8 ha92aebf_0
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - html5lib
        - isodate
        - pyparsing
        - python >=3.7,<3.8.0a0
        - sparqlwrapper
test:
    commands:
        - rdfpipe --help
        - rdfgraphisomorphism --help
    imports:
        - rdflib
        - rdflib.extras
        - rdflib.plugins
        - rdflib.plugins.parsers
        - rdflib.plugins.parsers.pyMicrodata
        - rdflib.plugins.parsers.pyRdfa
        - rdflib.plugins.parsers.pyRdfa.extras
        - rdflib.plugins.parsers.pyRdfa.host
        - rdflib.plugins.parsers.pyRdfa.rdfs
        - rdflib.plugins.parsers.pyRdfa.transform
        - rdflib.plugins.serializers
        - rdflib.plugins.sparql
        - rdflib.plugins.sparql.results
        - rdflib.plugins.stores
        - rdflib.tools
about:
    dev_url: https://github.com/RDFLib/rdflib
    doc_url: https://rdflib.readthedocs.io
    home: https://github.com/RDFLib/rdflib
    license: BSD 3-Clause
    license_file: LICENSE
    summary: RDFLib is a Python library for working with RDF, a simple yet powerful
        language for representing information.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - satra
