# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 27 19:04:19 2019
# ------------------------------------------------

package:
    name: font-ttf-inconsolata
    version: '2.001'
source:
    sha256: 9ef2f20e4fe8f062f365a98dde498f3fca06c9d5b1b7b29a63be8c9691ef116f
    url: https://github.com/google/fonts/archive/e301650445524f7f80837ed04d8b9d3806e33d5e.zip
build:
    noarch: generic
    number: '0'
    string: hab24e00_0
test:
    commands:
        - test -f ${PREFIX}/fonts/Inconsolata-Regular.ttf
        - test -f ${PREFIX}/fonts/Inconsolata-Bold.ttf
    requires:
        - bzip2
about:
    home: https://fonts.google.com/specimen/Inconsolata
    license: OFL
    license_family: Other
    license_file: ofl/inconsolata/OFL.txt
    summary: Monospace font for pretty code listings
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dbast
