# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /opt/recipe, last modified Fri Jul  6 21:46:19 2018
# ------------------------------------------------

package:
    name: perl-io-html
    version: '1.001'
source:
    md5: 3f8958718844dc96b9f6946f21d70d22
    url: http://cpan.metacpan.org/authors/id/C/CJ/CJM/IO-HTML-1.001.tar.gz
build:
    number: '2'
    string: pl526_2
requirements:
    build:
        - libgcc-ng 7.2.0 hdf63c60_3
        - perl 5.26.2 h470a237_0
    run:
        - perl >=5.26.2,<5.27.0a0
test:
    imports:
        - IO::HTML
about:
    home: http://metacpan.org/pod/IO-HTML
    license: perl_5
    summary: Open an HTML file with automatic charset detection
extra:
    copy_test_source_files: true
    final: true
