# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jun  2 10:47:31 2020
# ------------------------------------------------

package:
    name: yaml
    version: 0.2.5
source:
    sha256: fa240dbf262be053f3898006d502d514936c818e422afdcf33921c63bed9bf2e
    url: https://github.com/yaml/libyaml/archive/0.2.5.tar.gz
build:
    number: '0'
    run_exports:
        - yaml >=0.2.5,<0.3.0a0
    string: h516909a_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.2 pl526_0
        - binutils_impl_linux-64 2.34 h53a641e_4
        - binutils_linux-64 2.34 hc952b39_20
        - gcc_impl_linux-64 7.5.0 hd420e75_6
        - gcc_linux-64 7.5.0 h09487f9_20
        - ld_impl_linux-64 2.34 h53a641e_4
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - libtool 2.4.6 h14c3975_1002
        - m4 1.4.18 h14c3975_1001
        - make 4.3 h516909a_0
        - perl 5.26.2 h516909a_1006
        - sysroot_linux-64 2.12 h3a0023d_5
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
    run:
        - libgcc-ng >=7.5.0
test:
    commands:
        - test -f "${PREFIX}/include/yaml.h"
        - test -f "${PREFIX}/lib/libyaml${SHLIB_EXT}"
about:
    description: 'YAML is a human friendly data serialization standard for all programming

        languages.

        '
    dev_url: https://github.com/yaml
    doc_source_url: https://github.com/yaml/www.yaml.org/tree/master/docs
    doc_url: http://www.yaml.org/spec/1.2/spec.html
    home: http://pyyaml.org/wiki/LibYAML
    license: MIT
    license_file: License
    summary: A C library for parsing and emitting YAML
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
        - seanyen
