# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Oct 15 03:33:23 2020
# ------------------------------------------------

package:
    name: nbformat
    version: 5.0.8
source:
    sha256: f545b22138865bfbcc6b1ffe89ed5a2b8e2dc5d4fe876f2ca60d8e6f702a30f8
    url: https://pypi.io/packages/source/n/nbformat/nbformat-5.0.8.tar.gz
build:
    entry_points:
        - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/nbformat_1602732862338/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py39h079e4ff_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.9.0 h2a148a8_4_cpython
        - python_abi 3.9 1_cp39
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py39h079e4ff_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - tzdata 2020b h516909a_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - ipython_genutils
        - jsonschema >=2.4,!=2.5.0
        - jupyter_core
        - python >=3.5
        - traitlets >=4.1
test:
    commands:
        - pip check
        - jupyter-trust -h
    imports:
        - nbformat
    requires:
        - pip
about:
    home: http://jupyter.org
    license: BSD-3-Clause
    license_file: COPYING.md
    summary: The Jupyter Notebook format
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - minrk
        - mpacer
        - ocefpaf
        - pelson
        - takluyver
