# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /opt/recipe, last modified Sun Jul  8 12:29:19 2018
# ------------------------------------------------

package:
    name: perl-parent
    version: '0.236'
source:
    sha256: 2d837ebd04f6aa4b8634c9fa9d0bead83f1bee4a8072defe862ee6eb82be127a
    url: https://cpan.metacpan.org/authors/id/C/CO/CORION/parent-0.236.tar.gz
build:
    number: '1'
    string: pl526_1
requirements:
    build:
        - libgcc-ng 7.2.0 hdf63c60_3
        - perl 5.26.2 h470a237_0
        - perl-extutils-makemaker 7.34 pl526_0
    run:
        - perl >=5.26.2,<5.27.0a0
test:
    commands:
        - perl -e "use parent"
about:
    home: http://metacpan.org/pod/parent
    license: perl_5
    summary: Establish an ISA relationship with base classes at compile time
extra:
    copy_test_source_files: true
    final: true
