# This file created by conda-build 3.19.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Mar 19 12:51:42 2020
# ------------------------------------------------

package:
    name: graphite2
    version: 1.3.13
source:
    sha256: dd63e169b0d3cf954b397c122551ab9343e0696fb2045e1b326db0202d875f06
    url: https://github.com/silnrsi/graphite/releases/download/1.3.13/graphite2-1.3.13.tgz
build:
    detect_binary_files_with_prefix: true
    number: '1001'
    string: he1b5a44_1001
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.34 h53a641e_0
        - binutils_linux-64 2.34 hc952b39_18
        - bzip2 1.0.8 h516909a_2
        - ca-certificates 2019.11.28 hecc5488_0
        - cmake 3.16.4 h28c56e5_0
        - expat 2.2.9 he1b5a44_2
        - gcc_impl_linux-64 7.3.0 hd420e75_5
        - gcc_linux-64 7.3.0 h553295d_18
        - gxx_impl_linux-64 7.3.0 hdf63c60_5
        - gxx_linux-64 7.3.0 h553295d_18
        - krb5 1.16.4 h2fd8d38_0
        - ld_impl_linux-64 2.34 h53a641e_0
        - libcurl 7.68.0 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - libuv 1.34.0 h516909a_0
        - make 4.3 h516909a_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1e h516909a_0
        - rhash 1.3.6 h14c3975_1001
        - tk 8.6.10 hed695b0_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: http://graphite.sil.org/
    license: LGPLv2
    license_file: COPYING
    summary: A "smart font" system that handles the complexities of lesser-known languages
        of the world.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pkgw
