# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed May 13 11:36:20 2020
# ------------------------------------------------

package:
    name: jmespath
    version: 0.10.0
source:
    fn: jmespath-0.10.0.tar.gz
    sha256: b85d0567b8666149a93172712e68920734333c0ce7e89b78b3e987f71e5ed4f9
    url: https://pypi.org/packages/source/j/jmespath/jmespath-0.10.0.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/jmespath_1589369830981/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . -vv
    string: pyh9f0ad1d_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2020.4.5.1 hecc5488_0
        - certifi 2020.4.5.1 py36h9f0ad1d_0
        - ld_impl_linux-64 2.34 h53a641e_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1g h516909a_0
        - pip 20.1 pyh9f0ad1d_0
        - python 3.6.10 h8356626_1011_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 hf8c457e_0
        - setuptools 46.2.0 py36h9f0ad1d_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1006
    run:
        - python
test:
    imports:
        - jmespath
about:
    dev_url: https://github.com/jmespath/jmespath.py
    home: https://github.com/jmespath/jmespath.py
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: JSON Matching Expressions
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
        - xylar
