# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Jan  5 19:15:06 2020
# ------------------------------------------------

package:
    name: schema-salad
    version: 4.5.20191229160203
source:
    sha256: fce45d4f4575c0783c18694fdaf5fde5193768829c2d211baa75fa0fa22a6933
    url: https://pypi.io/packages/source/s/schema-salad/schema-salad-4.5.20191229160203.tar.gz
build:
    entry_points:
        - schema-salad-doc=schema_salad.makedoc:main
        - schema-salad-tool=schema_salad.main:main
    number: '0'
    script: '/home/conda/feedstock_root/build_artifacts/schema-salad_1578251796763/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps --ignore-installed -vvv '
    string: py37_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py37_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 hdf63c60_0
        - libstdcxx-ng 9.2.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 19.3.1 py37_0
        - python 3.7.6 h357f687_1
        - readline 8.0 hf8c457e_0
        - setuptools 44.0.0 py37_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.33.6 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    run:
        - cachecontrol >=0.11.7,<0.12
        - future
        - lockfile >=0.9
        - mistune >=0.8.1,<0.9
        - python >=3.7,<3.8.0a0
        - rdflib >=4.2.2,<4.3.0
        - rdflib-jsonld >=0.3.0,<0.5.0
        - requests >=1.0
        - ruamel.yaml >=0.12.4,<0.16
        - setuptools
        - six >=1.8.0
        - typing_extensions
test:
    commands:
        - schema-salad-tool --help
        - schema-salad-doc --help
    imports:
        - schema_salad
        - schema_salad.tests
about:
    dev_url: https://github.com/common-workflow-language/schema_salad
    home: https://github.com/common-workflow-language/schema_salad
    license: Apache Software
    license_family: APACHE
    license_file: LICENSE.txt
    summary: Schema Annotations for Linked Avro Data (SALAD)
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chapmanb
        - croth1
        - pvanheus
