# This file created by conda-build 3.20.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Sep  5 12:21:01 2020
# ------------------------------------------------

package:
    name: attrs
    version: 20.2.0
source:
    fn: attrs-20.2.0.tar.gz
    sha256: 26b54ddbbb9ee1d34d5d3668dd37d6cf74990ab23c828c2888dccdceee395594
    url: https://pypi.io/packages/source/a/attrs/attrs-20.2.0.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install . --no-deps --ignore-installed
    string: pyh9f0ad1d_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9f0ad1d_0
        - ld_impl_linux-64 2.34 hc38a660_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - pip 20.2.2 py_0
        - python 3.6.11 h4d41432_2_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py36h9f0ad1d_0
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - python
test:
    imports:
        - attr
    requires:
        - coverage
        - hypothesis
        - pympler
        - six
        - zope
        - zope.interface
about:
    description: 'attrs is the Python package that will bring back the joy of writing

        classes by relieving you from the drudgery of implementing object

        protocols (aka dunder methods). Its main goal is to help you to write

        concise and correct software without slowing down your code. For that, it

        gives you a class decorator and a way to declaratively define the

        attributes on that class:

        '
    dev_url: https://github.com/python-attrs/attrs
    doc_url: https://attrs.readthedocs.io/en/stable/
    home: https://attrs.readthedocs.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: attrs is the Python package that will bring back the joy of writing classes
        by relieving you from the drudgery of implementing object protocols (aka dunder
        methods).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - CJ-Wright
        - jochym
        - licode
        - nicoddemus
