# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Dec 13 14:59:18 2019
# ------------------------------------------------

package:
    name: xorg-libxpm
    version: 3.5.13
source:
    sha256: 9cd1da57588b6cb71450eff2273ef6b657537a9ac4d02d0014228845b935ac25
    url: https://www.x.org/releases/individual/lib/libXpm-3.5.13.tar.bz2
build:
    detect_binary_files_with_prefix: true
    number: '0'
    string: h516909a_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he1b5a44_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_2
        - gcc_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.2.0 hdf63c60_0
        - libstdcxx-ng 9.2.0 hdf63c60_0
        - make 4.2.1 h14c3975_2004
        - pkg-config 0.29.2 h14c3975_1005
    host:
        - _libgcc_mutex 0.1 main
        - gettext 0.19.8.1 hc5be6a0_1002
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 hdf63c60_0
        - libstdcxx-ng 9.2.0 hdf63c60_0
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - pthread-stubs 0.4 h14c3975_1001
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.10 h516909a_0
        - xorg-libsm 1.2.3 h84519dc_1000
        - xorg-libx11 1.6.9 h516909a_0
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-libxext 1.3.4 h516909a_0
        - xorg-libxt 1.1.5 h516909a_1003
        - xorg-util-macros 1.19.2 h14c3975_1001
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
    run:
        - gettext >=0.19.8.1,<1.0a0
        - libgcc-ng >=7.3.0
        - xorg-libx11 1.6.*
        - xorg-libxext 1.3.*
        - xorg-libxt 1.1.*
        - xorg-xextproto
        - xorg-xproto
test:
    commands:
        - test -f $PREFIX/lib/libXpm.so
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: https://www.x.org/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: The X.org X11 pixmap library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pkgw
