# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 27 18:56:18 2019
# ------------------------------------------------

package:
    name: font-ttf-source-code-pro
    version: '2.030'
source:
    sha256: a4e4dd59b8e0a436b934f0f612c2e91b5932910c6d1c3b7d1a5a9f389c86302b
    url: https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.tar.gz
build:
    noarch: generic
    number: '0'
    string: hab24e00_0
test:
    commands:
        - test -f ${PREFIX}/fonts/SourceCodePro-Black.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-BlackIt.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-Bold.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-BoldIt.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-ExtraLight.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-ExtraLightIt.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-It.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-Light.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-LightIt.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-Medium.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-MediumIt.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-Regular.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-Semibold.ttf
        - test -f ${PREFIX}/fonts/SourceCodePro-SemiboldIt.ttf
    requires:
        - bzip2
about:
    home: https://adobe-fonts.github.io/source-code-pro/
    license: SIL Open Font Lic., Version 1.1
    license_family: Other
    license_file: LICENSE.txt
    summary: A set of fonts that have been designed to work well in UI environments
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dbast
