# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /opt/recipe, last modified Wed Aug  8 09:15:48 2018
# ------------------------------------------------

package:
    name: perl-test-requiresinternet
    version: '0.05'
source:
    sha256: bba7b32a1cc0d58ce2ec20b200a7347c69631641e8cae8ff4567ad24ef1e833e
    url: https://cpan.metacpan.org/authors/id/M/MA/MALLEN/Test-RequiresInternet-0.05.tar.gz
build:
    number: '0'
    string: pl526_0
requirements:
    build:
        - libgcc-ng 7.2.0 hdf63c60_3
        - perl 5.26.2 h470a237_0
        - perl-extutils-makemaker 7.34 pl526_0
        - perl-socket 2.027 pl526_1
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-socket
test:
    imports:
        - Test::RequiresInternet
about:
    home: https://metacpan.org/dist/Test-RequiresInternet
    license: perl_5
    summary: Easily test network connectivity
extra:
    copy_test_source_files: true
    final: true
