# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Oct 14 12:45:25 2020
# ------------------------------------------------

package:
    name: terminado
    version: 0.9.1
source:
    sha256: 3da72a155b807b01c9e8a5babd214e052a0a45a975751da3521a1c3381ce6d76
    url: https://pypi.io/packages/source/t/terminado/terminado-0.9.1.tar.gz
build:
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/terminado_1602679584439/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . --no-deps -vv
    string: py37hc8dfbb8_1
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - brotlipy 0.7.0 py37hb5d75c8_1001
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py37he5f6b98_2
        - cffi 1.14.3 py37h00ebd2e_1
        - chardet 3.0.4 py37he5f6b98_1008
        - cryptography 3.1.1 py37hff6837a_1
        - docutils 0.16 py37he5f6b98_2
        - flit 3.0.0 py_1
        - flit-core 3.0.0 py_1
        - idna 2.10 pyh9f0ad1d_0
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - pycparser 2.20 pyh9f0ad1d_2
        - pyopenssl 19.1.0 py_1
        - pysocks 1.7.1 py37he5f6b98_2
        - python 3.7.8 h6f2ec95_1_cpython
        - python_abi 3.7 1_cp37m
        - pytoml 0.1.21 py_0
        - readline 8.0 he28a2e2_2
        - requests 2.24.0 pyh9f0ad1d_0
        - requests_download 0.1.2 py_1
        - setuptools 49.6.0 py37he5f6b98_2
        - six 1.15.0 pyh9f0ad1d_0
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - urllib3 1.25.10 py_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - ptyprocess
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - tornado >=4
test:
    commands:
        - python -m pip check
    imports:
        - terminado
    requires:
        - pip
        - pytest
        - pytest-azurepipelines
        - pytest-cov
about:
    description: 'This is a Tornado websocket backend for the Xterm.js Javascript
        terminal emulator library.

        '
    dev_url: https://github.com/jupyter/terminado
    doc_source_url: https://github.com/jupyter/terminado/blob/master/doc/index.rst
    doc_url: http://terminado.readthedocs.org/en/latest/
    home: https://github.com/jupyter/terminado
    license: BSD-2-Clause
    license_file: LICENSE
    summary: Terminals served by tornado websockets
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - blink1073
        - bollwyvl
        - ocefpaf
        - pelson
        - takluyver
