CI: azure
c_compiler: gcc
c_compiler_version: '7'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
curl: '7.64'
cxx_compiler: gxx
docker_image: condaforge/linux-anvil-comp7
expat: '2.2'
extend_keys:
- ignore_version
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
libiconv: '1.15'
lua: '5'
numpy: '1.11'
openssl: 1.1.1a
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  curl:
    max_pin: x
  expat:
    max_pin: x.x
  libiconv:
    max_pin: x.x
  openssl:
    max_pin: x.x.x
  perl:
    max_pin: x.x.x
  tk:
    max_pin: x.x
  zlib:
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
tk: '8.6'
zlib: '1.2'
