# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Sep 11 18:17:20 2019
# ------------------------------------------------

package:
    name: git
    version: 2.23.0
source:
    -   folder: code
        patches:
            - 0001-macOS-Do-not-use-the-system-Wish-urgh.patch
        sha256: 7d84f5d6f48e95b467a04a8aa1d474e0d21abc7877998af945568d2634fea46a
        url: https://github.com/git/git/archive/v2.23.0.tar.gz
    -   folder: manpages
        sha256: a5b0998f95c2290386d191d34780d145ea67e527fac98541e0350749bf76be75
        url: https://mirrors.edge.kernel.org/pub/software/scm/git/git-manpages-2.23.0.tar.gz
build:
    detect_binary_files_with_prefix: true
    number: '2'
    string: pl526hce37bd2_2
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - autoconf 2.69 pl526h14c3975_9
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - m4 1.4.18 h14c3975_1001
        - make 4.2.1 h14c3975_2004
        - perl 5.26.2 h516909a_1006
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.6.16 hecc5488_0
        - curl 7.64.1 hf8cf82a_0
        - expat 2.2.5 he1b5a44_1003
        - gettext 0.19.8.1 hc5be6a0_1002
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.64.1 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libiconv 1.15 h516909a_1005
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1a h14c3975_1001
        - pcre 8.41 hf484d3e_1003
        - perl 5.26.2 h516909a_1006
        - tk 8.6.9 hed695b0_1003
        - zlib 1.2.11 h516909a_1006
    run:
        - curl >=7.64.1,<8.0a0
        - expat >=2.2.5,<2.3.0a0
        - expat >=2.2.5,<2.3.0a0
        - gettext >=0.19.8.1,<1.0a0
        - libgcc-ng >=7.3.0
        - libiconv >=1.15,<1.16.0a0
        - libiconv >=1.15,<1.16.0a0
        - openssl >=1.1.1a,<1.1.2a
        - openssl >=1.1.1a,<1.1.2a
        - pcre >=8.41,<9.0a0
        - perl >=5.26.2,<5.26.3.0a0
        - tk >=8.6.9,<8.7.0a0
        - tk >=8.6.9,<8.7.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f $PREFIX/bin/git
        - test -f $PREFIX/bin/gitk
        - test -f $PREFIX/libexec/git-core/git-add--interactive
        - git --version
        - git clone https://github.com/conda-forge/git-feedstock
        - bash $PREFIX/share/bash-completion/completions/git
        - conda inspect linkages -p $PREFIX $PKG_NAME
        - test -f $PREFIX/man/man1/git.1
about:
    home: https://git-scm.com/
    license: GPL v2 and LGPL 2.1
    license_file: code/COPYING
    summary: distributed version control system
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dougalsutherland
        - jakirkham
        - msarahan
        - ocefpaf
        - pelson
        - scopatz
