# This file created by conda-build 3.20.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Sep  8 13:36:51 2020
# ------------------------------------------------

package:
    name: pip
    version: 20.2.3
source:
    sha256: 30c70b6179711a7c4cf76da89e8a0f5282279dfb0278bec7b94134be92543b6d
    url: https://pypi.io/packages/source/p/pip/pip-20.2.3.tar.gz
build:
    disable_pip: true
    entry_points:
        - pip = pip._internal.cli.main:main
        - pip3 = pip._internal.cli.main:main
    noarch: python
    number: '0'
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h32f6830_0
        - ld_impl_linux-64 2.34 hc38a660_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1g h516909a_1
        - python 3.8.5 h1103e12_7_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py38h32f6830_0
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - python >=3
        - setuptools
        - wheel
test:
    commands:
        - pip -h
        - pip list
    imports:
        - pip
about:
    dev_url: https://github.com/pypa/pip
    doc_url: https://pip.pypa.io/en/stable/
    home: https://pip.pypa.io/en/stable/
    license: MIT
    license_family: MIT
    license_file: LICENSE.txt
    summary: PyPA recommended tool for installing Python packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - pelson
