# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Sep 29 01:23:26 2020
# ------------------------------------------------

package:
    name: nest-asyncio
    version: 1.4.1
source:
    patches:
        - 0001-Prevent-infinite-loop-when-asyncio.sleep-0-is-used-i.patch
    sha256: b86c3193abda5b2eeccf8c79894bc71c680369a178f4b068514ac00720b14e01
    url: https://pypi.io/packages/source/n/nest_asyncio/nest_asyncio-1.4.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/nest-asyncio_1601342677072/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h32f6830_0
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.8.5 h1103e12_9_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py38h32f6830_1
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - python >=3.5
test:
    imports:
        - nest_asyncio
about:
    description: 'By design asyncio does not allow its event loop to be nested.

        This presents a practical problem - when in an environment where the event
        loop is already running it''s impossible to run tasks and wait for the result.

        Trying to do so will give the error RuntimeError - This event loop is already
        running.

        The issue pops up in various environments, such as web servers, GUI applications
        and in Jupyter notebooks.

        This module patches asyncio to allow nested use of asyncio.run and loop.run_until_complete.

        '
    dev_url: https://github.com/erdewit/nest_asyncio
    doc_url: https://github.com/erdewit/nest_asyncio
    home: https://github.com/erdewit/nest_asyncio
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Patch asyncio to allow nested event loops
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - yehoshuadimarsky
