# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 25 19:25:23 2020
# ------------------------------------------------

package:
    name: xorg-libx11
    version: 1.6.12
source:
    fn: xorg-libX11-1.6.12.tar.bz2
    patches:
        - macos-sed-workaround.patch
    sha256: f108227469419ac04d196df0f3b80ce1f7f65059bb54c0de811f4d8e03fd6ec7
    url: https://www.x.org/releases/individual/lib/libX11-1.6.12.tar.bz2
build:
    always_include_files:
        - include/X11/ImUtil.h
        - include/X11/XKBlib.h
        - include/X11/Xcms.h
        - include/X11/Xlib-xcb.h
        - include/X11/Xlib.h
        - include/X11/XlibConf.h
        - include/X11/Xlibint.h
        - include/X11/Xlocale.h
        - include/X11/Xregion.h
        - include/X11/Xresource.h
        - include/X11/Xutil.h
        - include/X11/cursorfont.h
    detect_binary_files_with_prefix: true
    number: '0'
    string: h516909a_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.2 pl526_1
        - binutils_impl_linux-64 2.34 h2122c62_9
        - binutils_linux-64 2.34 h47ac705_27
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 hf34d7eb_27
        - gettext 0.19.8.1 hc5be6a0_1002
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.34 hc38a660_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - libtool 2.4.6 h516909a_1003
        - m4 1.4.18 h14c3975_1001
        - make 4.3 h516909a_0
        - perl 5.26.2 h516909a_1006
        - pkg-config 0.29.2 h516909a_1006
        - sed 4.8 hbfbb72e_0
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libxcb 1.13 h14c3975_1002
        - pthread-stubs 0.4 h14c3975_1001
        - xorg-inputproto 2.3.2 h14c3975_1002
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-util-macros 1.19.2 h14c3975_1001
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xorg-xtrans 1.4.0 h516909a_0
    run:
        - libgcc-ng >=7.5.0
        - libxcb 1.*
        - xorg-kbproto
        - xorg-xproto
test:
    commands:
        - test -f $PREFIX/lib/libX11.so
        - test -f $PREFIX/lib/libX11-xcb.so
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: https://www.x.org/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: The main client library for X Windows version 11.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pkgw
