# This file created by conda-build 3.20.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Sep  7 10:54:31 2020
# ------------------------------------------------

package:
    name: unzip
    version: '6.0'
source:
    sha256: 036d96991646d0449ed0aa952e4fbe21b476ce994abc276e49d30e686708bd37
    url: ftp://ftp.info-zip.org/pub/infozip/src/unzip60.tgz
build:
    number: '2'
    script:
        - make -f unix/Makefile CC=$CC prefix="$PREFIX" CF="$CFLAGS -I. -DNO_LCHMOD"
            LFLAGS1="$LDFLAGS" unzips
        - make prefix="$PREFIX" -f unix/Makefile install
    string: h516909a_2
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.34 h2122c62_9
        - binutils_linux-64 2.34 h47ac705_27
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 hf34d7eb_27
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.34 hc38a660_9
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - make 4.3 h516909a_0
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
    run:
        - libgcc-ng >=7.5.0
test:
    commands:
        - unzip -h
        - zipinfo -h
        - test "$(strings $(which unzip) | grep -ci lchmod)" -eq 0
about:
    home: http://www.info-zip.org/
    license: LicenseRef-BSD-like
    license_file: LICENSE
    summary: simple program for unzipping files
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chrisburr
        - jerowe
        - msarahan
