# This file created by conda-build 3.10.9
# meta.yaml template originally from:
# /opt/recipe, last modified Tue Jul 10 05:13:30 2018
# ------------------------------------------------

package:
    name: perl-xml-sax-base
    version: '1.09'
source:
    sha256: 66cb355ba4ef47c10ca738bd35999723644386ac853abbeb5132841f5e8a2ad0
    url: https://cpan.metacpan.org/authors/id/G/GR/GRANTM/XML-SAX-Base-1.09.tar.gz
build:
    number: '0'
    string: pl526_0
requirements:
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - perl 5.26.2 h470a237_0
        - perl-extutils-makemaker 7.34 pl526_0
    run:
        - perl >=5.26.2,<5.27.0a0
test:
    imports:
        - XML::SAX::Base
about:
    home: http://metacpan.org/pod/XML-SAX-Base
    license: perl_5
    summary: Base class for SAX Drivers and Filters
extra:
    copy_test_source_files: true
    final: true
