# This file created by conda-build 3.16.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Nov  9 13:46:05 2018
# ------------------------------------------------

package:
    name: ruamel.yaml
    version: 0.15.77
source:
    sha256: aa19db7cc000c863f7f887a9d2268aafe4e04e4767befc63cab58f1de7ec1fd6
    url: https://pypi.io/packages/source/r/ruamel.yaml/ruamel.yaml-0.15.77.tar.gz
build:
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/ruamel.yaml_1541771315323/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37h470a237_0
requirements:
    build:
        - toolchain 2.3.0 0
        - toolchain_c_linux-64 2.3.0 0
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.10.15 ha4d7672_0
        - certifi 2018.10.15 py37_1000
        - libffi 3.2.1 hfc679d8_5
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2p h470a237_1
        - pip 18.1 py37_1000
        - python 3.7.0 h5001a0f_4
        - readline 7.0 haf1bffa_1
        - setuptools 40.5.0 py37_0
        - sqlite 3.25.3 hb1c47c0_0
        - tk 8.6.8 ha92aebf_0
        - wheel 0.32.2 py37_0
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - libgcc-ng >=4.9
        - python >=3.7,<3.8.0a0
        - setuptools
test:
    imports:
        - ruamel.yaml
about:
    home: https://bitbucket.org/ruamel/yaml
    license: MIT
    license_file: LICENSE
    summary: A YAML package for Python. It is a derivative of Kirill Simonov's PyYAML
        3.11 which supports YAML1.1
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - mbargull
        - mwcraig
        - ocefpaf
        - pelson
