CI: azure
c_compiler: gcc
c_compiler_version: '7'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
ctng_cpu_arch: x86_64
ctng_target_platform: linux-64
ctng_vendor: conda_cos6
cxx_compiler: gxx
docker_image: condaforge/linux-anvil-comp7
extend_keys:
- ignore_build_only_deps
- extend_keys
- ignore_version
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.11'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
zip_keys:
- - ctng_cpu_arch
  - ctng_vendor
  - ctng_target_platform
