# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Oct 13 01:18:16 2020
# ------------------------------------------------

package:
    name: jsonschema
    version: 3.2.0
source:
    sha256: c8a85b28d377cc7737e46e2d9f2b4f44ee3c0e1deac6bf46ddefc7187d30797a
    url: https://pypi.io/packages/source/j/jsonschema/jsonschema-3.2.0.tar.gz
build:
    entry_points:
        - jsonschema = jsonschema.cli:main
    noarch: python
    number: '2'
    script: /home/conda/feedstock_root/build_artifacts/jsonschema_1602551949684/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps -vv
    string: py_2
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py39h079e4ff_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.9.0 h852b56e_3_cpython
        - python_abi 3.9 1_cp39
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py39h079e4ff_2
        - setuptools-scm 4.1.2 pyh9f0ad1d_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - toml 0.10.1 pyh9f0ad1d_0
        - tzdata 2020b h516909a_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - attrs >=17.4.0
        - importlib_metadata
        - pyrsistent >=0.14.0
        - python >=3.6
        - setuptools
        - six >=1.11.0
test:
    commands:
        - python -m pip check
        - jsonschema --help
    imports:
        - jsonschema
    requires:
        - pip
about:
    description: 'jsonschema is an implementation of JSON Schema for Python

        (supporting 2.7+ including Python 3)

        '
    dev_url: https://github.com/Julian/jsonschema
    doc_source_url: https://github.com/Julian/jsonschema/blob/v3.2.0/docs/index.rst
    doc_url: https://python-jsonschema.readthedocs.org
    home: https://github.com/Julian/jsonschema
    license: MIT
    license_file: COPYING
    summary: An implementation of JSON Schema validation for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - bollwyvl
        - minrk
        - nehaljwani
        - ocefpaf
