# This file created by conda-build 3.19.2
# ------------------------------------------------

package:
    name: libblas
    version: 3.8.0
source:
    patches:
        - patches/0001-Test-BLAS-and-LAPACKE-in-addition-to-LAPACK.patch
    sha256: deb22cc4a6120bff72621155a9917f485f96ef8319ac074a7afbc68aab88bcf6
    url: http://www.netlib.org/lapack/lapack-3.8.0.tar.gz
build:
    number: 17
    run_exports:
        - libblas >=3.8.0,<4.0a0
    string: 17_openblas
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_llvm
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgfortran-ng 7.5.0 hdf63c60_6
        - libopenblas 0.3.10 h5ec1e0e_0
        - llvm-openmp 10.0.0 hc9558a2_0
    run:
        - libopenblas >=0.3.10,<0.3.11.0a0
        - libopenblas >=0.3.10,<1.0a0
    run_constrained:
        - blas * openblas
        - libcblas 3.8.0 17_openblas
        - liblapack 3.8.0 17_openblas
        - liblapacke 3.8.0 17_openblas
test:
    commands:
        - test -f $PREFIX/lib/libblas.so.3
about:
    home: https://github.com/conda-forge/blas-feedstock
    license: BSD-3-Clause
    license_file:
        - LICENSE.txt
    summary: Metapackage to select the BLAS variant. Use conda's pinning mechanism
        in your environment to control which variant you want.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - isuruf
        - jakirkham
        - ocefpaf
        - pelson
