# This file created by conda-build 3.19.2
# ------------------------------------------------

package:
    name: libnghttp2
    version: 1.41.0
source:
    sha256: eacc6f0f8543583ecd659faf0a3f906ed03826f1d4157b536b4b385fe47c5bb8
    url: https://github.com/nghttp2/nghttp2/releases/download/v1.41.0/nghttp2-1.41.0.tar.gz
build:
    number: 2
    run_exports:
        - libnghttp2 >=1.41.0,<2.0a0
    string: h8cfc5f6_2
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.34 h2122c62_9
        - binutils_linux-64 2.34 h47ac705_27
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 hf34d7eb_27
        - gxx_impl_linux-64 7.5.0 h64c220c_13
        - gxx_linux-64 7.5.0 ha781d05_27
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.34 hc38a660_9
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - make 4.3 h516909a_0
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - c-ares 1.16.1 h516909a_3
        - ca-certificates 2020.6.20 hecda079_0
        - libev 4.33 h516909a_0
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - openssl 1.1.1g h516909a_1
        - zlib 1.2.11 h516909a_1007
    run:
        - c-ares >=1.16.1,<2.0a0
        - c-ares >=1.7.5
        - libev >=4.11
        - libev >=4.33,<4.34.0a0
        - libgcc-ng >=7.5.0
        - libstdcxx-ng >=7.5.0
        - openssl >=1.1.1g,<1.1.2a
        - openssl >=1.1.1g,<1.1.2a
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - nghttp -nv https://nghttp2.org
        - test ! -f ${PREFIX}/lib/libnghttp2.a
        - test -f ${PREFIX}/lib/libnghttp2.so
about:
    description: 'This is an implementation of the Hypertext Transfer Protocol version
        2 in C.


        The framing layer of HTTP/2 is implemented as a reusable C library. On top

        of that, we have implemented an HTTP/2 client, server and proxy. We have

        also developed load test and benchmarking tools for HTTP/2.

        '
    dev_url: https://github.com/nghttp2/nghttp2
    doc_url: https://nghttp2.org/documentation/
    home: http://github.com/nghttp2/nghttp2
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: This is an implementation of Hypertext Transfer Protocol version 2.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - cpaulik
        - mariusvniekerk
        - wolfv
