# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 27 23:29:22 2019
# ------------------------------------------------

package:
    name: pydotplus
    version: 2.0.2
source:
    fn: pydotplus-2.0.2.tar.gz
    md5: 0e2fc3dbdfd846819d4cd3769cb4595b
    patches:
        - 0001-Detect-graphviz-executables-with-bat-extension.patch
    url: https://pypi.io/packages/source/p/pydotplus/pydotplus-2.0.2.tar.gz
build:
    noarch: python
    number: '3'
    script: python -m pip install --no-deps --ignore-installed .
    string: pyhd1c1de3_3
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.6.16 hecc5488_0
        - cairo 1.16.0 hfb77d84_1002
        - certifi 2019.6.16 py27_1
        - expat 2.2.5 he1b5a44_1003
        - fontconfig 2.13.1 h86ecdb6_1001
        - freetype 2.10.0 he983fc9_0
        - fribidi 1.0.5 h516909a_1002
        - gettext 0.19.8.1 hc5be6a0_1002
        - glib 2.58.3 h6f030ca_1002
        - graphite2 1.3.13 hf484d3e_1000
        - graphviz 2.40.1 h5933667_1
        - harfbuzz 2.4.0 h9f30f68_2
        - icu 64.2 he1b5a44_0
        - jpeg 9c h14c3975_1001
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libiconv 1.15 h516909a_1005
        - libpng 1.6.37 hed695b0_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtiff 4.0.10 h57b8799_1003
        - libtool 2.4.6 h14c3975_1002
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.9 hee79883_2
        - lz4-c 1.8.3 he1b5a44_1001
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pango 1.42.4 he7ab937_0
        - pcre 8.41 hf484d3e_1003
        - pip 19.2.1 py27_0
        - pixman 0.38.0 h516909a_1003
        - pthread-stubs 0.4 h14c3975_1001
        - pyparsing 2.4.1.1 py_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 41.0.1 py27_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - wheel 0.33.4 py27_0
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.10 h516909a_0
        - xorg-libsm 1.2.3 h84519dc_1000
        - xorg-libx11 1.6.8 h516909a_0
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-libxext 1.3.4 h516909a_0
        - xorg-libxpm 3.5.12 h14c3975_1002
        - xorg-libxrender 0.9.10 h516909a_1002
        - xorg-libxt 1.1.5 h516909a_1003
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
        - zstd 1.4.0 h3b9ef0a_0
    run:
        - graphviz >=2.40.1,<3.0a0
        - pyparsing >=2.0.1
        - python
test:
    imports:
        - pydotplus
about:
    home: http://pydotplus.readthedocs.org/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Python interface to Graphviz's Dot language
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - satra
