# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /opt/recipe, last modified Sat Aug 10 20:27:37 2019
# ------------------------------------------------

package:
    name: perl-io-compress
    version: '2.087'
source:
    sha256: 94f792775d0496fffe862363c76637e74ff5b46c40cf47042547686d164e23cb
    url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/IO-Compress-2.087.tar.gz
build:
    number: '0'
    string: pl526he1b5a44_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - perl 5.26.2 h516909a_1006
        - perl-compress-raw-bzip2 2.087 pl526he1b5a44_0
        - perl-compress-raw-zlib 2.087 pl526hc9558a2_0
        - perl-extutils-makemaker 7.36 pl526_1
        - perl-scalar-list-utils 1.51 pl526h516909a_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - perl >=5.26.2,<5.26.3.0a0
        - perl-compress-raw-bzip2 >=2.087
        - perl-compress-raw-zlib >=2.087
        - perl-scalar-list-utils
test:
    imports:
        - IO::Compress::Adapter::Bzip2
        - IO::Compress::Adapter::Deflate
        - IO::Compress::Adapter::Identity
        - IO::Compress::Base
        - IO::Compress::Base::Common
        - IO::Compress::Bzip2
        - IO::Compress::Deflate
        - IO::Compress::Gzip
        - IO::Compress::Gzip::Constants
        - IO::Compress::RawDeflate
        - IO::Compress::Zip
        - IO::Compress::Zip::Constants
        - IO::Compress::Zlib::Constants
        - IO::Compress::Zlib::Extra
        - IO::Uncompress::Adapter::Bunzip2
        - IO::Uncompress::Adapter::Identity
        - IO::Uncompress::Adapter::Inflate
        - IO::Uncompress::AnyInflate
        - IO::Uncompress::AnyUncompress
        - IO::Uncompress::Base
        - IO::Uncompress::Bunzip2
        - IO::Uncompress::Gunzip
        - IO::Uncompress::Inflate
        - IO::Uncompress::RawInflate
        - IO::Uncompress::Unzip
about:
    home: http://metacpan.org/pod/IO-Compress
    license: perl_5
    summary: IO Interface to compressed data files/buffers
extra:
    copy_test_source_files: true
    final: true
