# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Mar  1 12:44:48 2019
# ------------------------------------------------

package:
    name: cwltool
    version: 1.0.20190228155703
source:
    sha256: 61771670640b67fd17dde9e026fbe5a83853d92d4b316e064d9904725e2787e4
    url: https://pypi.io/packages/source/c/cwltool/cwltool-1.0.20190228155703.tar.gz
build:
    entry_points:
        - cwltool=cwltool.main:run
    number: '0'
    script: '/home/conda/feedstock_root/build_artifacts/cwltool_1551444376696/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps --ignore-installed -vvv '
    string: py37_0
requirements:
    host:
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2018.11.29 ha4d7672_0
        - certifi 2018.11.29 py37_1000
        - libffi 3.2.1 hf484d3e_1005
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_0
        - pip 19.0.3 py37_0
        - python 3.7.1 h381d211_1002
        - readline 7.0 hf8c457e_1001
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 h67949de_1000
        - tk 8.6.9 h84994c4_1000
        - wheel 0.33.1 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - bagit >=1.6.4
        - mypy_extensions
        - prov ==1.5.1
        - psutil
        - python >=3.7,<3.8.0a0
        - rdflib >=4.2.2,<4.3.0
        - requests >=2.6.1
        - ruamel.yaml >=0.12.4,<=0.15.77
        - scandir
        - schema-salad >=4.1,<5
        - setuptools
        - shellescape >=3.4.1,<3.5
        - six >=1.9.0
        - typing_extensions
test:
    commands:
        - cwltool --help
    imports:
        - cwltool
        - cwltool.tests
about:
    doc_url: https://github.com/common-workflow-language/cwltool
    home: https://www.commonwl.org/
    license: Apache Software
    license_family: APACHE
    license_file: LICENSE.txt
    summary: Common workflow language reference implementation
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chapmanb
        - croth1
