# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Oct 10 06:27:39 2019
# ------------------------------------------------

package:
    name: pyasn1-modules
    version: 0.2.7
source:
    fn: pyasn1-modules-0.2.7.tar.gz
    sha256: 0c35a52e00b672f832e5846826f1fb7507907f7d52fba6faa9e3c4cbe874fe4b
    url: https://pypi.io/packages/source/p/pyasn1-modules/pyasn1-modules-0.2.7.tar.gz
build:
    noarch: python
    number: '0'
    script: python setup.py install --single-version-externally-managed --record=record.txt
    string: py_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.9.11 hecc5488_0
        - certifi 2019.9.11 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 41.4.0 py27_0
        - sqlite 3.30.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1003
        - zlib 1.2.11 h516909a_1006
    run:
        - pyasn1 >=0.4.6,<0.5.0
        - python
test:
    imports:
        - pyasn1_modules
about:
    dev_url: https://github.com/etingof/pyasn1-modules
    doc_url: http://pyasn1.sourceforge.net/
    home: http://pyasn1.sourceforge.net/
    license: BSD 2-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: A collection of ASN.1-based protocols modules.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - pmlandwehr
