# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /opt/recipe, last modified Sun Oct 27 15:04:54 2019
# ------------------------------------------------

package:
    name: transdecoder
    version: 5.5.0
source:
    sha256: c800d9226350817471e9f51267c91f7cab99dbc9b26c980527fc1019e7d90a76
    url: https://github.com/TransDecoder/TransDecoder/archive/TransDecoder-v5.5.0.tar.gz
build:
    noarch: generic
    number: '2'
    string: pl526_2
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - perl 5.26.2 h516909a_1006
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-db-file
        - perl-uri
test:
    commands:
        - TransDecoder.Predict --version | grep -q "TransDecoder.Predict 5.5.0"
        - TransDecoder.LongOrfs --version | grep -q "TransDecoder.LongOrfs 5.5.0"
        - 'start_codon_refinement.pl 2>&1 | grep -q optional:'
about:
    dev_url: https://github.com/TransDecoder/TransDecoder
    home: https://transdecoder.github.io/
    license: Broad Institute
    summary: TransDecoder identifies candidate coding regions within transcript sequences,
        such as those generated by de novo RNA-Seq transcript assembly using Trinity,
        or constructed based on RNA-Seq alignments to the genome using Tophat and
        Cufflinks.
extra:
    copy_test_source_files: true
    final: true
