# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Oct  7 14:09:25 2020
# ------------------------------------------------

package:
    name: sqlite
    version: 3.33.0
source:
    sha256: 106a2c48c7f75a298a7557bcc0d5f4f454e5b43811cc738b7ca294d6956bbb15
    url: https://www.sqlite.org/2020/sqlite-autoconf-3330000.tar.gz
build:
    number: '1'
    run_exports:
        - sqlite >=3.33.0,<4.0a0
    string: h4cf870e_1
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35 h18a2f87_9
        - binutils_linux-64 2.35 hc3fd857_29
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 he2a3fca_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35 h769bd43_9
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - libtool 2.4.6 h516909a_1005
        - make 4.3 h516909a_0
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_1
        - readline 8.0 he28a2e2_2
        - zlib 1.2.11 h516909a_1009
    run:
        - libgcc-ng >=7.5.0
        - ncurses >=6.2,<6.3.0a0
        - readline >=8.0,<9.0a0
        - readline >=8.0,<9.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - sqlite3 --version
        - test -f $PREFIX/lib/libsqlite3${SHLIB_EXT}
        - test ! -f $PREFIX/lib/libsqlite3.a
        - test -f $PREFIX/include/sqlite3.h
        - test -f $PREFIX/include/sqlite3ext.h
about:
    description: 'SQLite is a self-contained, high-reliability, embedded, full-featured,

        public-domain, SQL database engine.It is the most used database engine

        in the world.

        '
    dev_url: https://github.com/mackyle/sqlite
    doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
    doc_url: http://www.sqlite.org/docs.html
    home: http://www.sqlite.org/
    license: Public-Domain (http://www.sqlite.org/copyright.html)
    license_url: http://www.sqlite.org/copyright.html
    summary: Implements a self-contained, zero-configuration, SQL database engine
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - mingwandroid
        - msarahan
        - ocefpaf
        - snorfalorpagus
        - xylar
