# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jan 23 15:13:55 2020
# ------------------------------------------------

package:
    name: parallel
    version: '20200122'
source:
    fn: parallel-20200122.tar.bz2
    sha256: 116f1e428da5cdb26cda3ee5f249bdb20c5f96f139c0a284ad142919d6d80c1c
    url: http://ftpmirror.gnu.org/parallel/parallel-20200122.tar.bz2
build:
    number: '0'
    string: '0'
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - make 4.2.1 h14c3975_2004
    run:
        - perl
test:
    commands:
        - parallel --version
about:
    home: http://www.gnu.org/software/parallel/
    license: GPL-3
    license_family: GPL
    license_file: COPYING
    summary: GNU parallel is a shell tool for executing jobs in parallel using one
        or more computers.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - rvalieris
