# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Feb  3 15:46:31 2020
# ------------------------------------------------

package:
    name: google-cloud-core
    version: 1.3.0
source:
    fn: google-cloud-core-1.3.0.tar.gz
    sha256: 878f9ad080a40cdcec85b92242c4b5819eeb8f120ebc5c9f640935e24fc129d8
    url: https://pypi.io/packages/source/g/google-cloud-core/google-cloud-core-1.3.0.tar.gz
build:
    noarch: python
    number: '0'
    script: pip install . --no-deps -vv
    string: py_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 20.0.2 py27_1
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 44.0.0 py27_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py27_0
        - zlib 1.2.11 h516909a_1006
    run:
        - google-api-core >=1.16.0,<2.0.0dev
        - python
test:
    imports:
        - google.api_core.client_info
        - google.cloud.client
        - google.cloud.environment_vars
        - google.cloud.exceptions
        - google.cloud.operation
about:
    description: This library is not meant to stand-alone. Instead it defines common
        helpers (e.g. base Client and Connection classes) used by all of the  google-cloud-*.
    dev_url: https://github.com/googleapis/google-cloud-python/tree/master/core
    doc_url: https://googleapis.dev/python/google-cloud-core/latest/
    home: https://github.com/googleapis/google-cloud-python/tree/master/core
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: 'API Client library for Google Cloud: Core Helpers'
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - leahecole
        - parthea
        - tswast
