# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Aug 27 17:55:09 2019
# ------------------------------------------------

package:
    name: wand
    version: 0.5.6
source:
    sha256: d06b59f36454024ce952488956319eb542d5dc65f1e1b00fead71df94dbfcf88
    url: https://github.com/emcconville/wand/releases/download/0.5.6/Wand-0.5.6.tar.gz
build:
    noarch: python
    number: '0'
    script: '/home/conda/feedstock_root/build_artifacts/wand_1566928595625/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed -vvv '
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py27_1
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pip 19.2.3 py27_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 41.2.0 py27_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h516909a_1005
    run:
        - imagemagick
        - python
test:
    imports:
        - wand.image
about:
    home: https://github.com/emcconville/wand
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Wand is a ctypes-based simple ImageMagick binding for Python, supporting
        2.7, 3.6+, and PyPy
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - r78v10a07
