CI: azure
c_compiler: gcc
c_compiler_version: '7'
cairo: '1.16'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '7'
docker_image: condaforge/linux-anvil-comp7
expat: '2.2'
extend_keys:
- ignore_version
- pin_run_as_build
- ignore_build_only_deps
- extend_keys
fortran_compiler: gfortran
freetype: 2.9.1
ignore_build_only_deps:
- python
- numpy
jpeg: '9'
libpng: '1.6'
libtiff: 4.1.0
lua: '5'
numpy: '1.11'
pango: '1.42'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  cairo:
    max_pin: x.x
  expat:
    max_pin: x.x
  freetype:
    max_pin: x
  jpeg:
    max_pin: x
  libpng:
    max_pin: x.x
  libtiff:
    max_pin: x
  pango:
    max_pin: x.x
  zlib:
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
zlib: '1.2'
