# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Nov 26 12:24:58 2019
# ------------------------------------------------

package:
    name: graphviz
    version: 2.42.3
source:
    md5: 9f61dc85517957793c6bb24f0611eac1
    url: https://www2.graphviz.org/Packages/stable/portable_source/graphviz-2.42.3.tar.gz
build:
    detect_binary_files_with_prefix: true
    number: '0'
    string: h0511662_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.33.1 he1b5a44_7
        - binutils_linux-64 2.33.1 h9595d00_15
        - gcc_impl_linux-64 7.3.0 habb00fd_2
        - gcc_linux-64 7.3.0 h553295d_15
        - gxx_impl_linux-64 7.3.0 hdf63c60_2
        - gxx_linux-64 7.3.0 h553295d_15
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h14c3975_2004
    host:
        - _libgcc_mutex 0.1 main
        - cairo 1.16.0 hfb77d84_1002
        - expat 2.2.5 he1b5a44_1004
        - fontconfig 2.13.1 h86ecdb6_1001
        - freetype 2.9.1 he983fc9_1006
        - fribidi 1.0.5 h516909a_1002
        - gettext 0.19.8.1 hc5be6a0_1002
        - glib 2.58.3 h6f030ca_1002
        - graphite2 1.3.13 hf484d3e_1000
        - harfbuzz 2.4.0 h9f30f68_3
        - icu 64.2 he1b5a44_1
        - jpeg 9c h14c3975_1001
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libiconv 1.15 h516909a_1005
        - libpng 1.6.37 hed695b0_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libtiff 4.1.0 hc3755c2_1
        - libtool 2.4.6 h14c3975_1002
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.10 hee79883_0
        - lz4-c 1.8.3 he1b5a44_1001
        - pango 1.42.4 ha030887_1
        - pcre 8.43 he1b5a44_0
        - pixman 0.38.0 h516909a_1003
        - pthread-stubs 0.4 h14c3975_1001
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.10 h516909a_0
        - xorg-libsm 1.2.3 h84519dc_1000
        - xorg-libx11 1.6.9 h516909a_0
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-libxext 1.3.4 h516909a_0
        - xorg-libxpm 3.5.12 h516909a_1002
        - xorg-libxrender 0.9.10 h516909a_1002
        - xorg-libxt 1.1.5 h516909a_1003
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
        - zstd 1.4.4 h3b9ef0a_1
    run:
        - cairo >=1.16.0,<1.17.0a0
        - cairo >=1.16.0,<1.17.0a0
        - expat >=2.2.5,<2.3.0a0
        - expat >=2.2.5,<2.3.0a0
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - jpeg >=9c,<10a
        - jpeg >=9c,<10a
        - libgcc-ng >=7.3.0
        - libpng >=1.6.37,<1.7.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libstdcxx-ng >=7.3.0
        - libtiff >=4.1.0,<5.0a0
        - libtiff >=4.1.0,<5.0a0
        - libtool
        - libxcb
        - pango >=1.42.4,<1.43.0a0
        - xorg-libxpm
        - xorg-libxrender
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - dot -V
        - neato -?
        - conda inspect linkages $PKG_NAME
    files:
        - sample.dot
about:
    description: 'Graphviz is an open source graph visualization software. Graph visualization

        is a way of representing structural information as diagrams of abstract

        graphs and networks.

        '
    dev_url: https://gitlab.com/graphviz/graphviz/
    doc_url: https://graphviz.gitlab.io/documentation/
    home: http://www.graphviz.org/
    license: EPL-1.0
    license_family: Other
    license_file: COPYING
    summary: Open Source graph visualization software.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - jakirkham
        - johanneskoester
        - ocefpaf
