# This file created by conda-build 3.19.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Mar 15 12:01:07 2020
# ------------------------------------------------

package:
    name: mypy_extensions
    version: 0.4.3
source:
    fn: mypy_extensions-0.4.3.tar.gz
    sha256: 2d82818f5bb3e369420cb3c4060a7970edba416647068eb4c5343488a6c604a8
    url: https://pypi.io/packages/source/m/mypy_extensions/mypy_extensions-0.4.3.tar.gz
build:
    number: '1'
    script: '/home/conda/feedstock_root/build_artifacts/mypy_extensions_1584273723973/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
        -m pip install . --no-deps --ignore-installed -vvv '
    string: py37hc8dfbb8_1
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py37hc8dfbb8_1
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 20.0.2 py_2
        - python 3.7.6 h357f687_4_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 hf8c457e_0
        - setuptools 46.0.0 py37hc8dfbb8_2
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    run:
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
test:
    imports:
        - mypy_extensions
about:
    description: 'The ''mypy_extensions'' module defines experimental extensions to
        the

        standard ''typing'' module that are supported by the mypy typechecker.

        '
    dev_url: https://github.com/python/mypy/blob/master/extensions
    doc_url: https://mypy.readthedocs.io
    home: http://www.mypy-lang.org/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Experimental type system extensions for programs checked with the mypy
        typechecker.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
