# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Nov  4 20:21:13 2019
# ------------------------------------------------

package:
    name: testpath
    version: 0.4.4
source:
    sha256: 60e0a3261c149755f4399a1fff7d37523179a70fdc3abdf78de9fc2604aeec7e
    url: https://pypi.io/packages/source/t/testpath/testpath-0.4.4.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/testpath_1572898959688/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . --no-deps --ignore-installed -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - asn1crypto 1.2.0 py38_0
        - ca-certificates 2019.9.11 hecc5488_0
        - certifi 2019.9.11 py38_0
        - cffi 1.13.2 py38h8022711_0
        - chardet 3.0.4 py38_1003
        - cryptography 2.7 py38h72c5cf5_0
        - docutils 0.15.2 py38_0
        - flit 1.3 py38_0
        - idna 2.8 py38_1000
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pip 19.3.1 py38_0
        - pycparser 2.19 py38_1
        - pyopenssl 19.0.0 py38_0
        - pysocks 1.7.1 py38_0
        - python 3.8.0 h357f687_2
        - pytoml 0.1.21 py_0
        - readline 8.0 hf8c457e_0
        - requests 2.22.0 py38_1
        - requests_download 0.1.2 py_1
        - setuptools 41.6.0 py38_1
        - six 1.12.0 py38_1001
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.9 hed695b0_1003
        - urllib3 1.25.6 py38_0
        - wheel 0.33.6 py38_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    run:
        - python
test:
    imports:
        - testpath
about:
    description: 'Testpath contains functions to check things on the filesystem,

        and tools for mocking system commands and recording calls to those.

        '
    dev_url: https://github.com/jupyter/testpath
    doc_url: https://testpath.readthedocs.io
    home: https://testpath.readthedocs.io
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Testpath is a collection of utilities for Python code working with files
        and commands.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - ocefpaf
        - takluyver
