# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Nov  4 17:14:10 2019
# ------------------------------------------------

package:
    name: matplotlib-base
    version: 3.1.1
source:
    patches:
        - PR14891.patch
    sha256: 29d1a239bb7d1095d98d8831bb661519ab0d23e30d38ed47729f554f15e8cd3e
    url: https://github.com/matplotlib/matplotlib/archive/v3.1.1.tar.gz
build:
    number: '2'
    string: py37h250f245_2
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h7fc9f1b_2
        - binutils_linux-64 2.31.1 h6176602_12
        - gcc_impl_linux-64 7.3.0 habb00fd_2
        - gcc_linux-64 7.3.0 h553295d_12
        - gxx_impl_linux-64 7.3.0 hdf63c60_2
        - gxx_linux-64 7.3.0 h553295d_12
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - pkg-config 0.29.2 h14c3975_1005
    host:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h516909a_1
        - ca-certificates 2019.9.11 hecc5488_0
        - certifi 2019.9.11 py37_0
        - cycler 0.10.0 py_2
        - freetype 2.9.1 he983fc9_1006
        - icu 64.2 he1b5a44_1
        - libblas 3.8.0 14_openblas
        - libcblas 3.8.0 14_openblas
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_2
        - liblapack 3.8.0 14_openblas
        - libopenblas 0.3.7 h6e990d7_2
        - libpng 1.6.37 hed695b0_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - nose 1.3.7 py37_1003
        - numpy 1.14.6 py37h95a1406_1201
        - openssl 1.1.1c h516909a_0
        - pip 19.3.1 py37_0
        - pyparsing 2.4.2 py_0
        - python 3.7.3 h33d41f4_1
        - python-dateutil 2.8.1 py_0
        - readline 8.0 hf8c457e_0
        - setuptools 41.6.0 py37_1
        - six 1.12.0 py37_1001
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.9 hed695b0_1003
        - wheel 0.33.6 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    run:
        - cycler >=0.10
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - icu >=64.2,<65.0a0
        - icu >=64.2,<65.0a0
        - kiwisolver
        - libgcc-ng >=7.3.0
        - libpng >=1.6.37,<1.7.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libstdcxx-ng >=7.3.0
        - numpy >=1.14.6,<2.0a0
        - pyparsing
        - python >=3.7,<3.8.0a0
        - python-dateutil
        - setuptools
        - tk >=8.6.9,<8.7.0a0
        - tk >=8.6.9,<8.7.0a0
        - tornado
test:
    imports:
        - matplotlib
        - matplotlib._image
        - matplotlib._path
        - matplotlib._png
        - matplotlib._tri
        - matplotlib.backends._backend_agg
        - matplotlib.backends._tkagg
        - matplotlib.ft2font
        - matplotlib.pyplot
        - matplotlib.ttconv
        - mpl_toolkits
        - pylab
about:
    description: 'matplotlib is a python 2D plotting library which produces publication

        quality figures in a variety of hardcopy formats and interactive

        environments across platforms. matplotlib can be used in Python scripts,

        the Python and IPython shell (ala MATLAB or Mathematica), web

        application servers, and six graphical user interface toolkits.

        '
    dev_url: https://github.com/matplotlib/matplotlib/
    doc_url: http://matplotlib.org/contents.html
    home: http://matplotlib.org/
    license: PSF-based
    license_family: PSF
    license_file: LICENSE/LICENSE
    license_url: http://matplotlib.sourceforge.net/users/license.html
    summary: Publication quality figures in Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dopplershift
        - mdboom
        - ocefpaf
        - pelson
        - tacaswell
