# This file created by conda-build 3.19.2
# ------------------------------------------------

package:
    name: googleapis-common-protos
    version: 1.51.0
source:
    sha256: 013c91704279119150e44ef770086fdbba158c1f978a6402167d47d5409e226e
    url: https://pypi.io/packages/source/g/googleapis-common-protos/googleapis-common-protos-1.51.0.tar.gz
build:
    number: 2
    script: /home/conda/feedstock_root/build_artifacts/googleapis-common-protos-feedstock_1586528146378/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed --verbose
    string: py37hc8dfbb8_2
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2020.4.5.1 hecc5488_0
        - certifi 2020.4.5.1 py37hc8dfbb8_0
        - ld_impl_linux-64 2.34 h53a641e_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libprotobuf 3.11.4 h8b12597_0
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1f h516909a_0
        - pip 20.0.2 py_2
        - protobuf 3.11.4 py37h3340039_1
        - python 3.7.6 h8356626_5_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 hf8c457e_0
        - setuptools 46.1.3 py37hc8dfbb8_0
        - six 1.14.0 py_1
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1006
    run:
        - protobuf
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
test:
    imports:
        - google.api
        - google.api.annotations_pb2
        - google.api.auth_pb2
        - google.api.backend_pb2
        - google.api.billing_pb2
        - google.api.client_pb2
        - google.api.config_change_pb2
        - google.api.consumer_pb2
        - google.api.context_pb2
        - google.api.control_pb2
        - google.api.distribution_pb2
        - google.api.documentation_pb2
        - google.api.endpoint_pb2
        - google.api.field_behavior_pb2
        - google.api.http_pb2
        - google.api.httpbody_pb2
        - google.api.label_pb2
        - google.api.launch_stage_pb2
        - google.api.log_pb2
        - google.api.logging_pb2
        - google.api.metric_pb2
        - google.api.monitored_resource_pb2
        - google.api.monitoring_pb2
        - google.api.quota_pb2
        - google.api.resource_pb2
        - google.api.service_pb2
        - google.api.source_info_pb2
        - google.api.system_parameter_pb2
        - google.api.usage_pb2
        - google.longrunning
        - google.longrunning.operations_pb2
        - google.longrunning.operations_proto
        - google.longrunning.operations_proto_pb2
        - google.protobuf
        - google.protobuf.any_pb2
        - google.protobuf.any_test_pb2
        - google.protobuf.api_pb2
        - google.protobuf.compiler
        - google.protobuf.compiler.plugin_pb2
        - google.protobuf.descriptor
        - google.protobuf.descriptor_database
        - google.protobuf.descriptor_pb2
        - google.protobuf.descriptor_pool
        - google.protobuf.duration_pb2
        - google.protobuf.empty_pb2
        - google.protobuf.field_mask_pb2
        - google.protobuf.internal
        - google.protobuf.internal.any_test_pb2
        - google.protobuf.internal.api_implementation
        - google.protobuf.internal.containers
        - google.protobuf.internal.decoder
        - google.protobuf.internal.descriptor_database_test
        - google.protobuf.internal.descriptor_pool_test
        - google.protobuf.internal.descriptor_pool_test1_pb2
        - google.protobuf.internal.descriptor_pool_test2_pb2
        - google.protobuf.internal.descriptor_test
        - google.protobuf.internal.encoder
        - google.protobuf.internal.enum_type_wrapper
        - google.protobuf.internal.factory_test1_pb2
        - google.protobuf.internal.factory_test2_pb2
        - google.protobuf.internal.file_options_test_pb2
        - google.protobuf.internal.generator_test
        - google.protobuf.internal.import_test_package
        - google.protobuf.internal.import_test_package.inner_pb2
        - google.protobuf.internal.import_test_package.outer_pb2
        - google.protobuf.internal.json_format_test
        - google.protobuf.internal.message_factory_test
        - google.protobuf.internal.message_listener
        - google.protobuf.internal.message_set_extensions_pb2
        - google.protobuf.internal.message_test
        - google.protobuf.internal.missing_enum_values_pb2
        - google.protobuf.internal.more_extensions_dynamic_pb2
        - google.protobuf.internal.more_extensions_pb2
        - google.protobuf.internal.more_messages_pb2
        - google.protobuf.internal.no_package_pb2
        - google.protobuf.internal.packed_field_test_pb2
        - google.protobuf.internal.proto_builder_test
        - google.protobuf.internal.python_message
        - google.protobuf.internal.reflection_test
        - google.protobuf.internal.service_reflection_test
        - google.protobuf.internal.symbol_database_test
        - google.protobuf.internal.test_bad_identifiers_pb2
        - google.protobuf.internal.test_util
        - google.protobuf.internal.testing_refleaks
        - google.protobuf.internal.text_encoding_test
        - google.protobuf.internal.text_format_test
        - google.protobuf.internal.type_checkers
        - google.protobuf.internal.unknown_fields_test
        - google.protobuf.internal.well_known_types
        - google.protobuf.internal.well_known_types_test
        - google.protobuf.internal.wire_format
        - google.protobuf.internal.wire_format_test
        - google.protobuf.json_format
        - google.protobuf.map_proto2_unittest_pb2
        - google.protobuf.map_unittest_pb2
        - google.protobuf.message
        - google.protobuf.message_factory
        - google.protobuf.proto_builder
        - google.protobuf.pyext
        - google.protobuf.pyext.python_pb2
        - google.protobuf.reflection
        - google.protobuf.service
        - google.protobuf.service_reflection
        - google.protobuf.source_context_pb2
        - google.protobuf.struct_pb2
        - google.protobuf.symbol_database
        - google.protobuf.test_messages_proto2_pb2
        - google.protobuf.test_messages_proto3_pb2
        - google.protobuf.text_encoding
        - google.protobuf.text_format
        - google.protobuf.timestamp_pb2
        - google.protobuf.type_pb2
        - google.protobuf.util
        - google.protobuf.util.json_format_proto3_pb2
        - google.protobuf.wrappers_pb2
        - google.rpc
        - google.rpc.code_pb2
        - google.rpc.error_details_pb2
        - google.rpc.status_pb2
        - google.type
        - google.type.calendar_period_pb2
        - google.type.color_pb2
        - google.type.date_pb2
        - google.type.dayofweek_pb2
        - google.type.expr_pb2
        - google.type.fraction_pb2
        - google.type.latlng_pb2
        - google.type.money_pb2
        - google.type.postal_address_pb2
        - google.type.quaternion_pb2
        - google.type.timeofday_pb2
about:
    description: 'This package does not include the grpc extra requirements.


        This repository contains the original interface definitions of public

        Google APIs that support both REST and gRPC protocols. Reading the original

        interface definitions can provide a better understanding of Google APIs and

        help you to utilize them more efficiently. You can also use these definitions

        with open source tools to generate client libraries, documentation,

        and other artifacts.


        **Deprecated Python Versions**


        Python == 2.7

        - Python 2.7 support will be removed on January 1, 2020.

        - protobuf does not support Visual C++ 2008, windows py27 package not available

        '
    dev_url: https://github.com/googleapis/googleapis
    doc_url: https://github.com/googleapis/googleapis/blob/master/README.md
    home: https://github.com/googleapis/googleapis
    license: Apache 2.0
    license_family: APACHE
    license_file: LICENSE
    summary: Common protobufs used in Google APIs
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - BrentDorsey
        - leahecole
        - parthea
        - tswast
