# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Apr 12 12:19:32 2019
# ------------------------------------------------

package:
    name: networkx
    version: '2.3'
source:
    sha256: 8311ddef63cf5c5c5e7c1d0212dd141d9a1fe3f474915281b73597ed5f1d4e3d
    url: https://pypi.io/packages/source/n/networkx/networkx-2.3.zip
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/networkx_1555071725192/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - certifi 2019.3.9 py37_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - pip 19.0.3 py37_0
        - python 3.7.3 h5b0a415_0
        - readline 7.0 hf8c457e_1001
        - setuptools 41.0.0 py37_0
        - sqlite 3.26.0 h67949de_1001
        - tk 8.6.9 h84994c4_1001
        - wheel 0.33.1 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - decorator >=4.3.0
        - python >=3.5
        - setuptools
test:
    imports:
        - networkx
        - networkx.algorithms
        - networkx.algorithms.approximation
        - networkx.algorithms.assortativity
        - networkx.algorithms.bipartite
        - networkx.algorithms.centrality
        - networkx.algorithms.chordal
        - networkx.algorithms.coloring
        - networkx.algorithms.community
        - networkx.algorithms.components
        - networkx.algorithms.connectivity
        - networkx.algorithms.flow
        - networkx.algorithms.isomorphism
        - networkx.algorithms.link_analysis
        - networkx.algorithms.node_classification
        - networkx.algorithms.operators
        - networkx.algorithms.shortest_paths
        - networkx.algorithms.traversal
        - networkx.algorithms.tree
        - networkx.classes
        - networkx.drawing
        - networkx.generators
        - networkx.linalg
        - networkx.readwrite
        - networkx.readwrite.json_graph
        - networkx.utils
about:
    description: 'NetworkX is a Python language software package for the creation,

        manipulation, and study of the structure, dynamics, and functions of complex

        networks.

        '
    dev_url: https://github.com/networkx/networkx
    doc_url: http://networkx.github.io/documentation.html
    home: https://networkx.github.io/
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: Python package for creating and manipulating complex networks
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - synapticarbors
