# This file created by conda-build 3.20.3
# ------------------------------------------------

package:
    name: libgomp
    version: 9.3.0
source:
    path: /home/conda/recipe_root
build:
    binary_relocation: false
    detect_binary_files_with_prefix: false
    ignore_run_exports:
        - __glibc
        - libgcc-ng
    missing_dso_whitelist:
        - '*'
    number: 17
    run_exports:
        strong:
            - _openmp_mutex >=4.5
    string: h5dbcf3e_17
requirements:
    host:
        - _sysroot_linux-64_curr_repodata_hack 3 ha9d2b57_10
        - kernel-headers_linux-64 3.10.0 h77966d4_10
        - sysroot_linux-64 2.17 h77966d4_10
    run:
        - _libgcc_mutex 0.1 conda_forge
test:
    commands:
        - test -f ${PREFIX}/lib/libgomp.so.1.0.0
        - test ! -f ${PREFIX}/lib/libgomp.so.1
    requires:
        - sysroot_linux-64
about:
    home: https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html
    license: GPL-3.0-only WITH GCC-exception-3.1
    summary: The GCC OpenMP implementation.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - beckermr
        - isuruf
