# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Oct  3 22:58:26 2020
# ------------------------------------------------

package:
    name: zipp
    version: 3.3.0
source:
    patches:
        - use-scm-version.patch
    sha256: 64ad89efee774d1897a58607895d80789c59778ea02185dd846ac38394a8642b
    url: https://pypi.io/packages/source/z/zipp/zipp-3.3.0.tar.gz
build:
    noarch: python
    number: '0'
    script: '/home/conda/feedstock_root/build_artifacts/zipp_1601765966131/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
        -m pip install . --no-deps --ignore-installed -vv '
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h32f6830_0
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.8.5 h1103e12_9_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py38h32f6830_1
        - setuptools-scm 4.1.2 pyh9f0ad1d_0
        - setuptools_scm 4.1.2 0
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - toml 0.10.1 pyh9f0ad1d_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - python >=3.6
test:
    commands:
        - python -m unittest test_zipp.py
        - pip check
    imports:
        - zipp
    requires:
        - func_timeout
        - importlib_metadata
        - jaraco.itertools
        - pip
    source_files:
        - test_zipp.py
about:
    dev_url: https://github.com/jaraco/zipp
    doc_url: https://zipp.readthedocs.io/en/latest
    home: https://github.com/jaraco/zipp
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A pathlib-compatible Zipfile object wrapper
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
