# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/recipe, last modified Sat Mar  9 08:01:36 2019
# ------------------------------------------------

package:
    name: perl-ntlm
    version: '1.09'
source:
    md5: da314ee94b14af2a2f39b6f2c0046e73
    url: http://cpan.metacpan.org/authors/id/N/NB/NBEBOUT/NTLM-1.09.tar.gz
build:
    number: '4'
    string: pl526_4
requirements:
    host:
        - libgcc-ng 7.3.0 hdf63c60_0
        - perl 5.26.2 h14c3975_1002
        - perl-digest-hmac 1.03 pl526_3
    run:
        - perl >=5.26.2,<5.26.3.0a0
        - perl-digest-hmac
test:
    imports:
        - Authen::NTLM
about:
    home: http://metacpan.org/pod/NTLM
    license: perl_5
    summary: An NTLM authentication module
extra:
    copy_test_source_files: true
    final: true
