# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /opt/recipe, last modified Wed Aug 21 06:40:53 2019
# ------------------------------------------------

package:
    name: sra-tools
    version: 2.10.0
source:
    -   folder: sra-tools
        sha256: 6d2b02bad674cde6b9677a522f62da092da5471d23738976abce8eae5710fa0c
        url: https://github.com/ncbi/sra-tools/archive/2.10.0.tar.gz
    -   folder: ncbi-vdb
        sha256: a6cc88e8d12f536dc96d5f60698d0ef4cf2f63e31d3d12d23da39b1de39563e1
        url: https://github.com/ncbi/ncbi-vdb/archive/2.10.0.tar.gz
    -   folder: ngs
        sha256: 4139adff83af213d7880bc80d1c0f5ee9b00c6c4e615d00aa47aaa267e40ed25
        url: https://github.com/ncbi/ngs/archive/2.10.0.tar.gz
build:
    number: '0'
    string: pl526he1b5a44_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_8
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_8
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_8
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    host:
        - _libgcc_mutex 0.1 main
        - icu 64.2 he1b5a44_0
        - libgcc-ng 9.1.0 hdf63c60_0
        - libiconv 1.15 h516909a_1005
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libxml2 2.9.9 hee79883_2
        - ncbi-ngs-sdk 2.9.3 h550f44e_0
        - perl 5.26.2 h516909a_1006
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - ncbi-ngs-sdk
        - perl >=5.26.2,<5.26.3.0a0
        - perl-uri
        - perl-xml-libxml
test:
    commands:
        - fastq-dump --help > /dev/null
        - prefetch --help > /dev/null
        - sam-dump --help > /dev/null
        - sra-pileup --help > /dev/null
        - vdb-config --help > /dev/null
        - vdb-decrypt --help > /dev/null
        - fastq-dump -N 1 -X 1 SRR000001 && grep '@SRR000001.1' SRR000001.fastq
        - fasterq-dump --help > /dev/null
about:
    description: 'The SRA Toolkit and SDK from NCBI is a collection of tools and libraries

        for using data in the INSDC Sequence Read Archives.

        '
    home: https://github.com/ncbi/sra-tools
    license: Public Domain
    summary: SRA Toolkit and SDK from NCBI
extra:
    copy_test_source_files: true
    final: true
    notes: 'After installation, you should run the configuration tool: ./vdb-config
        -i. This tool will setup your download/cache area for downloaded files and
        references.'
