# This file created by conda-build 3.18.11
# ------------------------------------------------

package:
    name: gst-plugins-base
    version: 1.14.5
source:
    -   sha256: e40888752883177e97b2d90cd68591f87ccd213dc0178ff721d80a4cdaad34b5
        url: https://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.14.5.tar.xz
    -   folder: plugins_base
        sha256: 7bfa9b329ea7f3c654fa1b2d43650bf2646598a5e3cb21f42c516b7e975d638e
        url: https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.14.5.tar.xz
    -   folder: plugins_good
        sha256: 678221b3f0208b31b90df3ffa509857cc8bfc337f3f5073d195c5b365d616503
        url: https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.14.5.tar.xz
build:
    activate_in_script: true
    number: 2
    run_exports:
        - gst-plugins-base >=1.14.5,<1.15.0a0
    string: h0935bb2_2
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - autoconf 2.69 pl526h14c3975_9
        - automake 1.16.1 pl526_1003
        - binutils_impl_linux-64 2.33.1 h53a641e_8
        - binutils_linux-64 2.33.1 h9595d00_16
        - expat-cos6-x86_64 2.0.1 0
        - gcc_impl_linux-64 7.3.0 hd420e75_5
        - gcc_linux-64 7.3.0 h553295d_16
        - gxx_impl_linux-64 7.3.0 hdf63c60_5
        - gxx_linux-64 7.3.0 h553295d_16
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libdrm-cos6-x86_64 2.4.65 hd39d64f_0
        - libdrm-devel-cos6-x86_64 2.4.65 h5701c1a_0
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libselinux-cos6-x86_64 2.0.94 hc7b3062_0
        - libselinux-devel-cos6-x86_64 2.0.94 h87dd427_0
        - libsepol-cos6-x86_64 2.0.41 h6e2433f_0
        - libsepol-devel-cos6-x86_64 2.0.41 h5bbff73_0
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - libx11-common-cos6-x86_64 1.6.4 h023ea50_0
        - libx11-cos6-x86_64 1.6.4 h64a1553_0
        - libx11-devel-cos6-x86_64 1.6.4 hb9851ce_0
        - libxau-cos6-x86_64 1.0.6 h4888106_0
        - libxau-devel-cos6-x86_64 1.0.6 hf5ff492_0
        - libxdamage-cos6-x86_64 1.1.3 h8e310ee_0
        - libxdamage-devel-cos6-x86_64 1.1.3 0
        - libxext-cos6-x86_64 1.3.3 hc47956f_0
        - libxext-devel-cos6-x86_64 1.3.3 hf6a4bb0_0
        - libxfixes-cos6-x86_64 5.0.3 h3a64028_0
        - libxfixes-devel-cos6-x86_64 5.0.3 0
        - libxrender-cos6-x86_64 0.9.10 h41db5cd_0
        - libxrender-devel-cos6-x86_64 0.9.10 ha8151bf_0
        - libxxf86vm-cos6-x86_64 1.1.3 h3cd9653_0
        - libxxf86vm-devel-cos6-x86_64 1.1.3 0
        - m4 1.4.18 h14c3975_1001
        - make 4.2.1 h14c3975_2004
        - mesa-dri-drivers-cos6-x86_64 11.0.7 h6ae8bd2_0
        - mesa-dri1-drivers-cos6-x86_64 7.11 hd08e721_0
        - mesa-libgl-cos6-x86_64 11.0.7 h045e36e_0
        - mesa-libgl-devel-cos6-x86_64 11.0.7 h5a2c0ac_0
        - perl 5.26.2 h516909a_1006
        - pkg-config 0.29.2 h516909a_1006
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h8d4a98b_0
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - cairo 1.16.0 hfb77d84_1002
        - fontconfig 2.13.1 h86ecdb6_1001
        - freetype 2.10.0 he983fc9_1
        - gettext 0.19.8.1 hc5be6a0_1002
        - glib 2.58.3 py38h6f030ca_1002
        - gobject-introspection 1.58.2 py38h5503ade_1002
        - gstreamer >=1.14.5,<2.0a0
        - icu 64.2 he1b5a44_1
        - ld_impl_linux-64 2.33.1 h53a641e_8
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libiconv 1.15 h516909a_1005
        - libpng 1.6.37 hed695b0_0
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.10 hee79883_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pcre 8.43 he1b5a44_0
        - pixman 0.38.0 h516909a_1003
        - pthread-stubs 0.4 h14c3975_1001
        - python 3.8.1 h357f687_2
        - readline 8.0 hf8c457e_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.10 h516909a_0
        - xorg-libsm 1.2.3 h84519dc_1000
        - xorg-libx11 1.6.9 h516909a_0
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-libxext 1.3.4 h516909a_0
        - xorg-libxrender 0.9.10 h516909a_1002
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1006
    run:
        - glib >=2.58.3,<3.0a0
        - gstreamer >=1.14.5,<2.0a0
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - xz >=5.2.4,<5.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f $PREFIX/lib/libgstallocators-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstapp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstaudio-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstfft-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstpbutils-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstriff-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstrtp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstrtsp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstsdp-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgsttag-1.0${SHLIB_EXT}
        - test -f $PREFIX/lib/libgstvideo-1.0${SHLIB_EXT}
about:
    description: 'GStreamer Base Plug-ins is a well-groomed and well-maintained collection
        of

        GStreamer plug-ins and elements, spanning the range of possible types of

        elements one would want to write for GStreamer.

        '
    doc_source_url: https://github.com/GStreamer/gst-plugins-base/tree/master/docs
    summary: GStreamer Base Plug-ins
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - mingwandroid
        - msarahan
