# This file created by conda-build 3.17.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Dec 20 13:23:44 2018
# ------------------------------------------------

package:
    name: rdflib-jsonld
    version: 0.4.0
source:
    sha256: 144774786a2fc7de09b24a9309cbcccc78bc48b152536d2ea1c1df2ad715bc2d
    url: https://pypi.io/packages/source/r/rdflib-jsonld/rdflib-jsonld-0.4.0.tar.gz
build:
    number: '1000'
    script: '/home/conda/feedstock_root/build_artifacts/rdflib-jsonld_1545312424455/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python
        -m pip install . --no-deps --ignore-installed -vvv '
    string: py37_1000
requirements:
    host:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.11.29 ha4d7672_0
        - certifi 2018.11.29 py37_1000
        - libffi 3.2.1 hfc679d8_5
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_2
        - openssl 1.0.2p h470a237_1
        - pip 18.1 py37_1000
        - python 3.7.1 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.6.3 py37_0
        - sqlite 3.26.0 hb1c47c0_0
        - tk 8.6.9 ha92aebf_0
        - wheel 0.32.3 py37_0
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
    run:
        - python >=3.7,<3.8.0a0
        - rdflib >=4.2
        - setuptools
test:
    imports:
        - rdflib_jsonld
about:
    dev_url: https://github.com/RDFLib/rdflib-jsonld
    home: https://github.com/RDFLib/rdflib-jsonld
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE.md
    summary: rdflib extension adding JSON-LD parser and serializer
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - croth1
