# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Oct 15 13:38:13 2020
# ------------------------------------------------

package:
    name: widgetsnbextension
    version: 3.5.1
source:
    sha256: 079f87d87270bce047512400efd70238820751a11d2d8cb137a5a5bdbaf255c7
    url: https://pypi.io/packages/source/w/widgetsnbextension/widgetsnbextension-3.5.1.tar.gz
build:
    number: '2'
    script: /home/conda/feedstock_root/build_artifacts/widgetsnbextension_1602769155190/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: py37hc8dfbb8_2
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - argon2-cffi 20.1.0 py37h8f50634_2
        - async_generator 1.10 py_0
        - attrs 20.2.0 pyh9f0ad1d_0
        - backcall 0.2.0 pyh9f0ad1d_0
        - backports 1.0 py_2
        - backports.functools_lru_cache 1.6.1 py_0
        - bleach 3.2.1 pyh9f0ad1d_0
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py37he5f6b98_2
        - cffi 1.14.3 py37h00ebd2e_1
        - decorator 4.4.2 py_0
        - defusedxml 0.6.0 py_0
        - entrypoints 0.3 py37hc8dfbb8_1002
        - importlib-metadata 2.0.0 py_1
        - importlib_metadata 2.0.0 1
        - ipykernel 5.3.4 py37hc6149b9_1
        - ipython 7.18.1 py37hc6149b9_1
        - ipython_genutils 0.2.0 py_1
        - jedi 0.17.2 py37hc8dfbb8_1
        - jinja2 2.11.2 pyh9f0ad1d_0
        - jsonschema 3.2.0 py_2
        - jupyter_client 6.1.7 py_0
        - jupyter_core 4.6.3 py37hc8dfbb8_2
        - jupyterlab_pygments 0.1.2 pyh9f0ad1d_0
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libsodium 1.0.18 h516909a_1
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - markupsafe 1.1.1 py37hb5d75c8_2
        - mistune 0.8.4 py37h8f50634_1002
        - nbclient 0.5.0 py_0
        - nbconvert 6.0.7 py37hc8dfbb8_1
        - nbformat 5.0.8 py_0
        - ncurses 6.2 he1b5a44_2
        - nest-asyncio 1.4.1 py_0
        - notebook 6.1.4 py37hc8dfbb8_1
        - openssl 1.1.1h h516909a_0
        - packaging 20.4 pyh9f0ad1d_0
        - pandoc 2.11.0.1 hd18ef5c_0
        - pandocfilters 1.4.2 py_1
        - parso 0.7.1 pyh9f0ad1d_0
        - pexpect 4.8.0 pyh9f0ad1d_2
        - pickleshare 0.7.5 py_1003
        - pip 20.2.3 py_0
        - prometheus_client 0.8.0 pyh9f0ad1d_0
        - prompt-toolkit 3.0.8 py_0
        - ptyprocess 0.6.0 py_1001
        - pycparser 2.20 pyh9f0ad1d_2
        - pygments 2.7.1 py_0
        - pyparsing 2.4.7 pyh9f0ad1d_0
        - pyrsistent 0.17.3 py37h8f50634_1
        - python 3.7.8 h6f2ec95_1_cpython
        - python-dateutil 2.8.1 py_0
        - python_abi 3.7 1_cp37m
        - pyzmq 19.0.2 py37hac76be4_2
        - readline 8.0 he28a2e2_2
        - send2trash 1.5.0 py_0
        - setuptools 49.6.0 py37he5f6b98_2
        - six 1.15.0 pyh9f0ad1d_0
        - sqlite 3.33.0 h4cf870e_1
        - terminado 0.9.1 py37hc8dfbb8_1
        - testpath 0.4.4 py_0
        - tk 8.6.10 hed695b0_1
        - tornado 6.0.4 py37h8f50634_2
        - traitlets 5.0.4 py_1
        - wcwidth 0.2.5 pyh9f0ad1d_2
        - webencodings 0.5.1 py_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zeromq 4.3.3 he1b5a44_2
        - zipp 3.3.0 py_0
        - zlib 1.2.11 h516909a_1010
    run:
        - notebook >=4.4.1
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
test:
    imports:
        - widgetsnbextension
about:
    description: 'Interactive HTML widgets for Jupyter notebooks.

        '
    dev_url: https://github.com/jupyter-widgets/ipywidgets/tree/master/widgetsnbextension
    doc_url: https://pypi.python.org/pypi/widgetsnbextension
    home: http://ipython.org
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Interactive Widgets for Jupyter
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - jakirkham
        - jasongrout
        - minrk
        - ocefpaf
        - pbugnion
        - pelson
        - willingc
