# This file created by conda-build 3.17.7
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jan 22 21:22:22 2019
# ------------------------------------------------

package:
    name: cachecontrol
    version: 0.11.7
source:
    fn: CacheControl-0.11.7.tar.gz
    sha256: 8f7829d92584f1f2360ebfff4517ee359787d5b7dfa2ef9579f871b628745a1e
    url: https://pypi.io/packages/source/C/CacheControl/CacheControl-0.11.7.tar.gz
build:
    entry_points:
        - doesitcache = cachecontrol._cmd:main
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    host:
        - ca-certificates 2018.11.29 ha4d7672_0
        - certifi 2018.11.29 py27_1000
        - libffi 3.2.1 hf484d3e_1005
        - libgcc-ng 7.3.0 hdf63c60_0
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.0.2p h14c3975_1002
        - pip 18.1 py27_1000
        - python 2.7.15 h938d71a_1006
        - readline 7.0 hf8c457e_1001
        - setuptools 40.6.3 py27_0
        - sqlite 3.26.0 h67949de_1000
        - tk 8.6.9 h84994c4_1000
        - wheel 0.32.3 py27_0
        - zlib 1.2.11 h14c3975_1004
    run:
        - python
        - requests
test:
    commands:
        - doesitcache --help
    imports:
        - cachecontrol
about:
    description: 'CacheControl is a port of the caching algorithms in httplib2 for
        use with

        requests session object.

        It was written because httplib2''s better support for caching is often

        mitigated by its lack of threadsafety. The same is true of requests

        in terms of caching.

        '
    dev_url: https://github.com/ionrock/cachecontrol
    doc_url: http://cachecontrol.readthedocs.io/
    home: https://github.com/ionrock/cachecontrol
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE.txt
    summary: The httplib2 caching algorithms packaged up for use with requests
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dougalsutherland
