# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Oct 14 18:54:35 2020
# ------------------------------------------------

package:
    name: entrypoints
    version: '0.3'
source:
    sha256: c70dd71abe5a8c85e55e12c19bd91ccfeec11a6e99044204511f9ed547d48451
    url: https://pypi.io/packages/source/e/entrypoints/entrypoints-0.3.tar.gz
build:
    number: '1002'
    script:
        - flit build --format wheel
        - /home/conda/feedstock_root/build_artifacts/entrypoints_1602701733603/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
            -m pip install dist/entrypoints-0.3-py2.py3-none-any.whl --no-deps --ignore-installed
            --no-cache-dir -vvv
    string: py37hc8dfbb8_1002
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - brotlipy 0.7.0 py39h38d8fee_1001
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py39h079e4ff_2
        - cffi 1.14.3 py39h0da4893_1
        - chardet 3.0.4 py39h079e4ff_1008
        - cryptography 3.1.1 py39h3c970e7_1
        - docutils 0.16 py39h079e4ff_2
        - flit 3.0.0 py_1
        - flit-core 3.0.0 py_1
        - idna 2.10 pyh9f0ad1d_0
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - pycparser 2.20 pyh9f0ad1d_2
        - pyopenssl 19.1.0 py_1
        - pysocks 1.7.1 py39h079e4ff_2
        - python 3.9.0 h852b56e_3_cpython
        - python_abi 3.9 1_cp39
        - pytoml 0.1.21 py_0
        - readline 8.0 he28a2e2_2
        - requests 2.24.0 pyh9f0ad1d_0
        - requests_download 0.1.2 py_1
        - setuptools 49.6.0 py39h079e4ff_2
        - six 1.15.0 pyh9f0ad1d_0
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - tzdata 2020b h516909a_0
        - urllib3 1.25.10 py_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py37he5f6b98_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.7.8 h6f2ec95_1_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py37he5f6b98_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
test:
    imports:
        - entrypoints
about:
    home: https://entrypoints.readthedocs.io/
    license: MIT
    license_file: LICENSE
    summary: Discover and load entry points from installed packages
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - ocefpaf
        - pelson
        - takluyver
