# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Oct 10 22:22:04 2020
# ------------------------------------------------

package:
    name: fftw
    version: 3.3.8
source:
    fn: fftw-3.3.8.tar.gz
    patches:
        - cmake-fftw-version.patch
        - cmake-pc-install.patch
    sha256: 6113262f6e92c5bd474f2875fa1b01054c4ad5040f6b0da7c03c98821d9ae303
    url: http://www.fftw.org/fftw-3.3.8.tar.gz
build:
    number: '1112'
    run_exports:
        - fftw
    string: nompi_h7f3a6c3_1112
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35 h18a2f87_9
        - binutils_linux-64 2.35 hc3fd857_29
        - gcc_impl_linux-64 7.5.0 hd9e1a51_17
        - gcc_linux-64 7.5.0 he2a3fca_29
        - gfortran_impl_linux-64 7.5.0 hfca37b7_17
        - gfortran_linux-64 7.5.0 ha081f1e_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35 h769bd43_9
        - libgcc-devel_linux-64 7.5.0 h42c25f5_17
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgfortran4 7.5.0 hae1eefd_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - perl 5.26.2 h516909a_1006
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgfortran-ng 7.5.0 hae1eefd_17
        - libgfortran4 7.5.0 hae1eefd_17
        - libgomp 9.3.0 h5dbcf3e_17
        - make 4.3 h516909a_0
    run:
        - libgcc-ng >=7.5.0
        - libgfortran-ng
        - libgfortran4 >=7.5.0
test:
    commands:
        - 'strings ${PREFIX}/lib/libfftw3.a | grep -q dfftw || exit 1

            '
        - test -f ${PREFIX}/lib/libfftw3f.a || exit 1
        - test -f ${PREFIX}/lib/libfftw3.a || exit 1
        - test -f ${PREFIX}/lib/libfftw3l.a || exit 1
        - test -f ${PREFIX}/lib/libfftw3f_threads.a || exit 1
        - test -f ${PREFIX}/lib/libfftw3_threads.a || exit 1
        - test -f ${PREFIX}/lib/libfftw3l_threads.a || exit 1
        - test -f ${PREFIX}/lib/libfftw3f_omp.a || exit 1
        - test -f ${PREFIX}/lib/libfftw3_omp.a || exit 1
        - test -f ${PREFIX}/lib/libfftw3l_omp.a || exit 1
        - test -f ${PREFIX}/include/fftw3.h || exit 1
        - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libfftw3${SHLIB_EXT}']"
        - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libfftw3_threads${SHLIB_EXT}']"
        - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libfftw3f${SHLIB_EXT}']"
        - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libfftw3f_threads${SHLIB_EXT}']"
        - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libfftw3l${SHLIB_EXT}']"
        - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libfftw3l_threads${SHLIB_EXT}']"
        - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libfftw3_omp${SHLIB_EXT}']"
        - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libfftw3f_omp${SHLIB_EXT}']"
        - python -c "import ctypes; ctypes.cdll[r'${PREFIX}/lib/libfftw3l_omp${SHLIB_EXT}']"
    requires:
        - python =3.6
about:
    home: http://fftw.org
    license: GPL-2.0-or-later
    license_file: COPYING
    summary: The fastest Fourier transform in the west.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - alexbw
        - beckermr
        - egpbos
        - grlee77
        - jakirkham
        - jjhelmus
        - jschueller
