# This file created by conda-build 3.19.1
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Mar 22 22:25:05 2020
# ------------------------------------------------

package:
    name: google-cloud-sdk
    version: 281.0.0
source:
    sha256: 065ec26529a6d87c8dcf9cb472eae0110eecaf84c3b3c44c388a060c4cc6f103
    url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-281.0.0-linux-x86_64.tar.gz
build:
    number: '2'
    string: py37hc8dfbb8_2
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - ld_impl_linux-64 2.34 h53a641e_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1e h516909a_0
        - python 3.7.6 h357f687_4_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 hf8c457e_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - xz 5.2.4 h516909a_1002
        - zlib 1.2.11 h516909a_1006
    run:
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
test:
    commands:
        - gcloud version
        - gcloud components list
about:
    home: https://cloud.google.com/sdk/
    license: Apache v2.0
    license_family: Apache
    license_file: LICENSE
    summary: Command-line interface for Google Cloud Platform products and services
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - chapmanb
        - nehaljwani
        - scopatz
