# This file created by conda-build 3.18.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jul 23 11:37:15 2019
# ------------------------------------------------

package:
    name: qtpy
    version: 1.9.0
source:
    fn: qtpy-1.9.0.tar.gz
    sha256: 2db72c44b55d0fe1407be8fba35c838ad0d6d3bb81f23007886dc1fc0f459c8d
    url: https://pypi.io/packages/source/q/qtpy/QtPy-1.9.0.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py27_1
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pip 19.2 py27_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 41.0.1 py27_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - wheel 0.33.4 py27_0
        - zlib 1.2.11 h516909a_1005
    run:
        - python
test:
    imports:
        - qtpy
        - qtpy.QtGui
    requires:
        - pyqt
about:
    home: https://github.com/spyder-ide/qtpy
    license: MIT
    summary: A uniform layer to support PyQt5, PyQt4 and PySide with a single codebase
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - Nodd
        - astrofrog-conda-forge
        - ccordoba12
        - goanpeca
