# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jul 29 06:44:15 2020
# ------------------------------------------------

package:
    name: libssh2
    version: 1.9.0
source:
    patches:
        - 0001-libssh2-1.9.0-CVE-2019-17498.patch
        - 246c7cb0184b9e1a882c753b412825799c7a9118.patch
    sha256: d5fb8bd563305fd1074dda90bd053fb2d29fc4bce048d182f96eaa466dfadafd
    url: https://www.libssh2.org/download/libssh2-1.9.0.tar.gz
build:
    number: '5'
    run_exports:
        - libssh2 >=1.9.0,<2.0a0
    string: hab1572f_5
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.34 h2122c62_9
        - binutils_linux-64 2.34 h47ac705_22
        - cmake-no-system 3.16.4 he1b5a44_0
        - gcc_impl_linux-64 7.5.0 hda68d29_11
        - gcc_linux-64 7.5.0 ha781d05_22
        - kernel-headers_linux-64 2.6.32 h77966d4_12
        - ld_impl_linux-64 2.34 hc38a660_9
        - libgcc-ng 9.3.0 h24d8f2e_11
        - libgomp 9.3.0 h24d8f2e_11
        - libstdcxx-ng 9.3.0 hdf63c60_11
        - make 4.3 h516909a_0
        - sysroot_linux-64 2.12 h77966d4_12
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - libgcc-ng 9.3.0 h24d8f2e_11
        - libgomp 9.3.0 h24d8f2e_11
        - openssl 1.1.1g h516909a_0
        - zlib 1.2.11 h516909a_1006
    run:
        - libgcc-ng >=7.5.0
        - openssl >=1.1.1g,<1.1.2a
        - openssl >=1.1.1g,<1.1.2a
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
about:
    description: 'libssh2 is a library implementing the SSH2 protocol, available under
        the revised BSD license.

        '
    dev_url: https://github.com/libssh2/libssh2
    home: https://www.libssh2.org/
    license: BSD-3-Clause
    license_family: BSD
    license_file: COPYING
    summary: the SSH library
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nehaljwani
        - ocefpaf
        - shadowwalkersb
