# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jul 30 10:45:18 2019
# ------------------------------------------------

package:
    name: nodejs
    version: 12.3.0
source:
    fn: node-v12.3.0.tar.gz
    sha256: e26c54677964cb6b242a6221f3c121620564718f8be1e9a36a16f69860c575ea
    url: https://nodejs.org/dist/v12.3.0/node-v12.3.0.tar.gz
build:
    ignore_prefix_files:
        - bin/node
    number: '0'
    string: he1b5a44_0
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - ca-certificates 2019.6.16 hecc5488_0
        - curl 7.65.3 hf8cf82a_0
        - expat 2.2.5 he1b5a44_1003
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - gettext 0.19.8.1 hc5be6a0_1002
        - git 2.22.0 pl526hce37bd2_0
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_7
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.65.3 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libiconv 1.15 h516909a_1005
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h14c3975_2004
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - perl 5.26.2 h516909a_1006
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - zlib 1.2.11 h516909a_1005
    host:
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
test:
    commands:
        - node -h
        - node -v
        - npm version
        - npm install -h
        - npm config get prefix -g
        - test $(echo "console.log(1 + 3)" | node) == 4
about:
    home: https://nodejs.org/
    license: MIT
    license_file: LICENSE
    summary: a platform for easily building fast, scalable network applications
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - minrk
        - msarahan
        - pelson
