CI: azure
c_compiler: gcc
c_compiler_version: '7'
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: condaforge/linux-anvil-comp7
extend_keys:
- ignore_version
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
fortran_compiler: gfortran
giflib: '5.2'
ignore_build_only_deps:
- python
- numpy
jpeg: '9'
libpng: '1.6'
libtiff: 4.1.0
lua: '5'
numpy: '1.11'
perl: 5.26.0
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  jpeg:
    max_pin: x
  libpng:
    max_pin: x.x
  libtiff:
    max_pin: x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
