# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Nov  2 19:04:09 2019
# ------------------------------------------------

package:
    name: backports.functools_lru_cache
    version: 1.6.1
source:
    sha256: 8fde5f188da2d593bd5bc0be98d9abc46c95bb8a9dde93429570192ee6cc2d4a
    url: https://pypi.io/packages/source/b/backports.functools_lru_cache/backports.functools_lru_cache-1.6.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1572721532190/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - backports 1.0 py_2
        - ca-certificates 2019.9.11 hecc5488_0
        - certifi 2019.9.11 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pip 19.3.1 py27_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 41.6.0 py27_1
        - setuptools_scm 3.3.3 py_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.9 hed695b0_1003
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h516909a_1006
    run:
        - backports
        - python
        - setuptools
test:
    imports:
        - backports.functools_lru_cache
about:
    dev_url: https://github.com/jaraco/backports.functools_lru_cache
    doc_url: https://pypi.python.org/pypi/backports.functools_lru_cache
    home: https://github.com/jaraco/backports.functools_lru_cache
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Backport of functools.lru_cache from Python 3.3 as published at ActiveState.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mariusvniekerk
        - stuertz
