# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jun 29 08:46:12 2020
# ------------------------------------------------

package:
    name: cachetools
    version: 4.1.1
source:
    sha256: bbaa39c3dede00175df2dc2b03d0cf18dd2d32a7de7beb68072d13043c9edb20
    url: https://pypi.io/packages/source/c/cachetools/cachetools-4.1.1.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/cachetools_1593420445823/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . -vv
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h32f6830_0
        - ld_impl_linux-64 2.34 h53a641e_5
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1g h516909a_0
        - pip 20.1.1 py_1
        - python 3.8.3 cpython_he5300dc_0
        - python_abi 3.8 1_cp38
        - readline 8.0 hf8c457e_0
        - setuptools 47.3.1 py38h32f6830_0
        - sqlite 3.32.3 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - xz 5.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1006
    run:
        - python >=3.5
test:
    commands:
        - pip check
    imports:
        - cachetools
    requires:
        - pip
about:
    description: 'This module provides various memoizing collections and decorators,
        including variants of the Python 3 Standard Library @lru_cache function decorator.

        '
    dev_url: https://github.com/tkem/cachetools
    doc_url: http://pythonhosted.org/cachetools/
    home: https://github.com/tkem/cachetools
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Extensible memoizing collections and decorators
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - maartenbreddels
        - marcelotrevisani
