# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Oct  1 21:19:22 2020
# ------------------------------------------------

package:
    name: glib
    version: 2.66.1
source:
    patches:
        - hardcoded-paths.patch
        - skip-gio-tests-meson.build.patch
        - skip-gio-tests-resources.c.patch
        - skip-glib-tests-fileutils.c.patch
    sha256: a269ffe69fbcc3a21ff1acb1b6146b2a5723499d6e2de33ae16ccb6d2438ef60
    url: http://ftp.gnome.org/pub/GNOME/sources/glib/2.66/glib-2.66.1.tar.xz
build:
    number: '0'
    run_exports:
        - glib >=2.66.1,<3.0a0
    string: h680cd38_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35 h18a2f87_9
        - binutils_linux-64 2.35 heab0d09_28
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py38h32f6830_0
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 hf34d7eb_28
        - gxx_impl_linux-64 7.5.0 h64c220c_13
        - gxx_linux-64 7.5.0 ha781d05_28
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - meson 0.55.3 py_0
        - ncurses 6.2 he1b5a44_1
        - ninja 1.10.1 hc9558a2_1
        - openssl 1.1.1h h516909a_0
        - pkg-config 0.29.2 h516909a_1006
        - python 3.8.5 h1103e12_9_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py38h32f6830_1
        - sqlite 3.33.0 h4cf870e_0
        - sysroot_linux-64 2.12 h77966d4_13
        - tk 8.6.10 hed695b0_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - gettext 0.19.8.1 hc5be6a0_1002
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libiconv 1.16 h516909a_0
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - pcre 8.44 he1b5a44_0
        - zlib 1.2.11 h516909a_1009
    run:
        - gettext >=0.19.8.1,<1.0a0
        - libffi >=3.2.1,<3.3.0a0
        - libffi >=3.2.1,<3.3.0a0
        - libgcc-ng >=7.5.0
        - libiconv >=1.16,<1.17.0a0
        - libiconv >=1.16,<1.17.0a0
        - libstdcxx-ng >=7.5.0
        - pcre >=8.44,<9.0a0
        - python >=2.7
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - test -f ${PREFIX}/lib/libglib-2.0.so
        - test ! -f ${PREFIX}/lib/libgobject-2.0.la
        - gapplication help
        - gdbus help
        - gio version
        - gio-querymodules .
        - glib-compile-resources --help
        - glib-compile-schemas --help
        - gobject-query --help
        - gresource help
        - gtester --help
about:
    home: https://developer.gnome.org/glib/
    license: LGPL-2.1-or-later
    license_file: COPYING
    summary: Provides core application building blocks for libraries and applications
        written in C.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ccordoba12
        - isuruf
        - jakirkham
        - ocefpaf
        - pkgw
        - scopatz
