# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Oct 11 01:43:43 2020
# ------------------------------------------------

package:
    name: pyyaml
    version: 5.3.1
source:
    patches:
        - 0001-Ensure-we-do-not-end-up-wih-CRLF-line-endings-on-tes.patch
    sha256: b8eac752c5e14d3eca0e6dd9199cd627518cb5ec06add0de9d32baeee6fe645d
    url: https://pypi.io/packages/source/P/PyYAML/PyYAML-5.3.1.tar.gz
build:
    number: '1'
    script:
        - python setup.py --with-libyaml build_ext --include-dirs="${PREFIX}/include"
            --library-dirs="${PREFIX}/lib"
        - python setup.py install
        - python setup.py test
    string: py37hb5d75c8_1
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35 h18a2f87_9
        - binutils_linux-64 2.35 hc3fd857_29
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 he2a3fca_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35 h769bd43_9
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - cython 0.29.21 py37hb892b2f_1
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1h h516909a_0
        - python 3.7.8 h6f2ec95_1_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 he28a2e2_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - xz 5.2.5 h516909a_1
        - yaml 0.2.5 h516909a_0
        - zlib 1.2.11 h516909a_1009
    run:
        - libgcc-ng >=7.5.0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
        - yaml >=0.2.5,<0.3.0a0
test:
    imports:
        - _yaml
        - yaml
about:
    dev_url: https://github.com/yaml/pyyaml
    doc_url: http://pyyaml.org/wiki/PyYAML
    home: http://pyyaml.org/wiki/PyYAML
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: YAML parser and emitter for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - msarahan
        - ocefpaf
        - pelson
