# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Jul 11 21:55:39 2020
# ------------------------------------------------

package:
    name: fribidi
    version: 1.0.10
source:
    patches:
        - meson-rpaths.patch
    sha256: 7f1c687c7831499bcacae5e8675945a39bacbad16ecaa945e9454a32df653c01
    url: https://github.com/fribidi/fribidi/releases/download/v1.0.10/fribidi-1.0.10.tar.xz
build:
    number: '0'
    run_exports:
        - fribidi >=1.0.10,<2.0a0
    string: h516909a_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - binutils_impl_linux-64 2.34 h53a641e_6
        - binutils_linux-64 2.34 hc952b39_20
        - ca-certificates 2020.6.20 hecda079_0
        - gcc_impl_linux-64 7.5.0 hd420e75_6
        - gcc_linux-64 7.5.0 h09487f9_20
        - ld_impl_linux-64 2.34 h53a641e_6
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - meson 0.54.3 py_0
        - ncurses 6.1 hf484d3e_1002
        - ninja 1.10.0 hc9558a2_0
        - openssl 1.1.1g h516909a_0
        - python 3.8.3 cpython_he5300dc_0
        - python_abi 3.8 1_cp38
        - readline 8.0 h46ee950_1
        - sqlite 3.32.3 hcee41ef_1
        - tk 8.6.10 hed695b0_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1006
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
    run:
        - libgcc-ng >=7.5.0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
        - fribidi -h
about:
    description: 'One of the missing links stopping the penetration of free software
        in Middle

        East is the lack of support for the Arabic and Hebrew alphabets. In order
        to

        have proper Arabic and Hebrew support, the bidi algorithm needs to be

        implemented. It is our hope that this library will stimulate more free

        software in the Middle Eastern countries.

        '
    dev_url: https://github.com/fribidi/fribidi
    doc_url: https://github.com/fribidi/fribidi
    home: https://github.com/fribidi/fribidi
    license: LGPL-2.1
    license_file: COPYING
    summary: The Free Implementation of the Unicode Bidirectional Algorithm.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - mariusvniekerk
        - msarahan
