# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jan 15 21:52:30 2020
# ------------------------------------------------

package:
    name: google-resumable-media
    version: 0.5.0
source:
    sha256: 2a8fd188afe1cbfd5998bf20602f76b0336aa892de88fe842a806b9a3ed78d2a
    url: https://pypi.io/packages/source/g/google-resumable-media/google-resumable-media-0.5.0.tar.gz
build:
    noarch: python
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/google-resumable-media_1579125201638/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python
        -m pip install . --no-deps -vv
    string: py_1
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 19.3.1 py27_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 45.0.0 py27_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h516909a_1006
    run:
        - python
        - six
    run_constrained:
        - requests >=2.18.0,<3.0.0dev
test:
    imports:
        - google
        - google.resumable_media
about:
    dev_url: https://github.com/googleapis/google-resumable-media-python
    doc_url: https://googleapis.github.io/google-resumable-media-python/latest/
    home: https://github.com/googleapis/google-resumable-media-python
    license: Apache-2.0
    license_family: APACHE
    license_file: LICENSE
    summary: Utilities for Google Media Downloads and Resumable Uploads
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - johanneskoester
        - leahecole
        - parthea
        - tswast
