# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /opt/recipe, last modified Wed Apr 17 15:51:36 2019
# ------------------------------------------------

package:
    name: perl-html-parser
    version: '3.72'
source:
    sha256: ec28c7e1d9e67c45eca197077f7cdc41ead1bb4c538c7f02a3296a4bb92f608b
    url: https://cpan.metacpan.org/authors/id/G/GA/GAAS/HTML-Parser-3.72.tar.gz
build:
    number: '5'
    string: pl526h6bb024c_5
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_3
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_3
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_3
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
    host:
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - perl 5.26.2 h516909a_1005
        - perl-app-cpanminus 1.7044 pl526_1
        - perl-carp 1.38 pl526_2
        - perl-constant 1.33 pl526_1
        - perl-exporter 5.72 pl526_1
        - perl-extutils-makemaker 7.34 pl526_3
        - perl-file-path 2.15 pl526_1
        - perl-file-temp 0.2304 pl526_2
        - perl-html-tagset 3.20 pl526_3
        - perl-parent 0.236 pl526_1
        - perl-storable 3.11 pl526_0
        - perl-test-simple 1.302156 pl526_0
        - perl-xsloader 0.24 pl526_0
    run:
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - perl >=5.26.2,<5.26.3.0a0
        - perl-html-tagset
        - perl-xsloader
test:
    imports:
        - HTML::Filter
        - HTML::Parser
about:
    home: http://metacpan.org/pod/HTML::Parser
    license: perl_5
    summary: HTML parser class
extra:
    copy_test_source_files: true
    final: true
