# This file created by conda-build 3.15.1
# meta.yaml template originally from:
# /opt/recipe, last modified Sat Mar  9 08:01:36 2019
# ------------------------------------------------

package:
    name: perl-digest-hmac
    version: '1.03'
source:
    md5: e6a5d6f552da16eacb5157ea4369ff9d
    url: http://cpan.metacpan.org/authors/id/G/GA/GAAS/Digest-HMAC-1.03.tar.gz
build:
    number: '3'
    string: pl526_3
requirements:
    host:
        - libgcc-ng 7.3.0 hdf63c60_0
        - perl 5.26.2 h14c3975_1002
    run:
        - perl >=5.26.2,<5.26.3.0a0
test:
    imports:
        - Digest::HMAC
about:
    home: http://metacpan.org/pod/Digest-HMAC
    license: perl_5
    summary: Keyed-Hashing for Message Authentication
extra:
    copy_test_source_files: true
    final: true
