# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Aug 21 15:33:23 2020
# ------------------------------------------------

package:
    name: bzip2
    version: 1.0.8
source:
    patches:
        - 0001-cross.patch
    sha256: ab5a03176ee106d3f0fa90e381da478ddae405918153cca248e682cd0c4a2269
    url: https://sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz
build:
    number: '3'
    run_exports:
        - bzip2 >=1.0.8,<2.0a0
    string: h516909a_3
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.34 h2122c62_9
        - binutils_linux-64 2.34 h47ac705_27
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 hf34d7eb_27
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.34 hc38a660_9
        - libgcc-ng 9.3.0 h24d8f2e_15
        - libgomp 9.3.0 h24d8f2e_15
        - libstdcxx-ng 9.3.0 hdf63c60_15
        - make 4.3 h516909a_0
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h24d8f2e_15
        - libgomp 9.3.0 h24d8f2e_15
    run:
        - libgcc-ng >=7.5.0
test:
    commands:
        - bzip2 --help
        - test -f ${PREFIX}/bin/bunzip2
        - test -f ${PREFIX}/bin/bzcat
        - test -f ${PREFIX}/bin/bzcmp
        - test -f ${PREFIX}/bin/bzdiff
        - test -f ${PREFIX}/bin/bzegrep
        - test -f ${PREFIX}/bin/bzfgrep
        - test -f ${PREFIX}/bin/bzgrep
        - test -f ${PREFIX}/bin/bzip2recover
        - test -f ${PREFIX}/bin/bzip2
        - test -f ${PREFIX}/bin/bzless
        - test -f ${PREFIX}/bin/bzmore
        - test -f ${PREFIX}/include/bzlib.h
        - test -f ${PREFIX}/lib/libbz2.a
        - test -f ${PREFIX}/lib/libbz2.so
about:
    description: 'Bzip2 is a freely available high-quality data compressor. It typically

        compresses files to within 10% to 15% of the best available techniques,

        whilst being around twice as fast at compression and six times faster

        at decompression.

        '
    doc_url: http://www.bzip.org/docs.html
    home: http://www.bzip.org/
    license: bzip2-1.0.6
    license_family: BSD
    license_file: LICENSE
    summary: high-quality data compressor
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - jjhelmus
        - jlanga
        - mingwandroid
        - msarahan
        - pelson
