# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Apr 10 09:21:38 2019
# ------------------------------------------------

package:
    name: ptyprocess
    version: 0.6.0
source:
    sha256: 923f299cc5ad920c68f2bc0bc98b75b9f838b93b599941a6b63ddbc2476394c0
    url: https://pypi.io/packages/source/p/ptyprocess/ptyprocess-0.6.0.tar.gz
build:
    noarch: python
    number: '1001'
    script:
        - flit build --format wheel
        - /home/conda/feedstock_root/build_artifacts/ptyprocess_1554888243421/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
            -m pip install dist/*.whl --no-deps -vv
    string: py_1001
requirements:
    host:
        - asn1crypto 0.24.0 py37_1003
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - certifi 2019.3.9 py37_0
        - cffi 1.12.2 py37hf0e25f4_1
        - chardet 3.0.4 py37_1003
        - cryptography 2.6.1 py37h72c5cf5_0
        - docutils 0.14 py37_1001
        - flit 1.3 py37_0
        - idna 2.8 py37_1000
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - pip 19.0.3 py37_0
        - pycparser 2.19 py37_1
        - pyopenssl 19.0.0 py37_0
        - pysocks 1.6.8 py37_1002
        - python 3.7.3 h5b0a415_0
        - pytoml 0.1.20 py_0
        - readline 7.0 hf8c457e_1001
        - requests 2.21.0 py37_1000
        - requests_download 0.1.2 py_1
        - setuptools 41.0.0 py37_0
        - six 1.12.0 py37_1000
        - sqlite 3.26.0 h67949de_1001
        - tk 8.6.9 h84994c4_1001
        - urllib3 1.24.1 py37_1000
        - wheel 0.33.1 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - python
test:
    imports:
        - ptyprocess
about:
    description: 'Ptyprocess allows you to launch a subprocess in a pseudo terminal
        (pty),

        and interact with both the process and its pty.

        '
    dev_url: https://github.com/pexpect/ptyprocess
    doc_source_url: https://github.com/pexpect/ptyprocess/blob/master/docs/index.rst
    doc_url: http://ptyprocess.readthedocs.io/en/latest/
    home: https://github.com/pexpect/ptyprocess
    license: ISC
    summary: Run a subprocess in a pseudo terminal
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pelson
        - takluyver
