CI: azure
_libgcc_mutex: 0.1 conda_forge
c_compiler: gcc
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
conda_glibc_ver: '2.12'
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
ctng_binutils: 2.31.1
ctng_cpu_arch: x86_64
ctng_gcc: 7.5.0
ctng_gcc_build_number: '17'
ctng_gmp: 6.1.2
ctng_isl: '0.22'
ctng_kernel: 2.6.32
ctng_libc: gnu
ctng_libiconv: '1.15'
ctng_mpc: '1'
ctng_nature: shared
ctng_ncurses: '6.1'
ctng_sample: x86_64-centos6-linux-gnu
ctng_target_platform: linux-64
ctng_vendor: conda
cxx_compiler: gxx
docker_image: condaforge/linux-anvil-comp7
extend_keys:
- ignore_build_only_deps
- ignore_version
- extend_keys
- pin_run_as_build
fortran_compiler: gfortran
gnu: 2.12.2
ignore_build_only_deps:
- numpy
- python
libgfortran_soname: '4'
libgomp_ver: 1.0.0
lua: '5'
numpy: '1.11'
old_ctng_vendor: conda_cos6
openmp_ver: '4.5'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.7'
r_base: '3.5'
target_platform: linux-64
zip_keys:
- - ctng_gcc
  - libgfortran_soname
- - conda_glibc_ver
  - old_ctng_vendor
  - gnu
  - ctng_kernel
  - ctng_sample
  - ctng_cpu_arch
  - ctng_binutils
  - ctng_target_platform
