# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Feb 14 19:10:30 2020
# ------------------------------------------------

package:
    name: google-auth
    version: 1.11.2
source:
    fn: google-auth-1.11.2.tar.gz
    sha256: 1ee22e22f35d6e00f068d7b3999b2ce24ecb5d0dcbd485aa6896d2b83c8907d6
    url: https://pypi.io/packages/source/g/google-auth/google-auth-1.11.2.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/google-auth_1581707487116/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/bin/python
        -m pip install . --no-deps -vv
    string: py_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 0_gnu
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.2.0 h24d8f2e_2
        - libgomp 9.2.0 h24d8f2e_2
        - libstdcxx-ng 9.2.0 hdf63c60_2
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d h516909a_0
        - pip 20.0.2 py_2
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 44.0.0 py27_0
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.34.2 py_1
        - zlib 1.2.11 h516909a_1006
    run:
        - cachetools >=2.0.0,<5.0
        - pyasn1-modules >=0.2.1
        - python
        - rsa >=3.1.4,<4.1
        - setuptools >=40.3.0
        - six >=1.9.0
test:
    commands:
        - python -m pip check
    imports:
        - google.auth
    requires:
        - pip
        - python
about:
    description: This library provides the ability to authenticate to Google APIs
        using various methods. It also provides integration with several HTTP libraries.
    dev_url: https://github.com/googleapis/google-auth-library-python
    doc_url: https://google-auth.readthedocs.io/en/latest/
    home: https://github.com/googleapis/google-auth-library-python
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE
    summary: Google authentication library for Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jreback
        - leahecole
        - parthea
        - theacodes
        - tswast
