# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Feb 12 17:30:39 2019
# ------------------------------------------------

package:
    name: cwl_runner
    version: '1.0'
source:
    sha256: 803ff93d63efd4f08198a41a4c39a1d22df220afd92bfb9bf69071dc45552100
    url: https://pypi.io/packages/source/c/cwl_runner/cwl_runner-1.0.tar.gz
build:
    entry_points:
        - cwl-runner=cwltool.main:main
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/cwl_runner_1549992726017/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . --no-deps --ignore-installed -vv
    string: py_0
requirements:
    host:
        - asn1crypto 0.24.0 py27_1003
        - bagit 1.7.0 py_0
        - ca-certificates 2018.11.29 ha4d7672_0
        - cachecontrol 0.12.5 py_0
        - certifi 2018.11.29 py27_1000
        - cffi 1.11.5 py27h9745a5d_1001
        - chardet 3.0.4 py27_1003
        - cryptography 2.5 py27hb7f436b_0
        - cwltool 1.0.20181217162649 py27_1001
        - decorator 4.3.2 py_0
        - enum34 1.1.6 py27_1001
        - html5lib 1.0.1 py_0
        - icu 58.2 hf484d3e_1000
        - idna 2.8 py27_1000
        - ipaddress 1.0.22 py_1
        - isodate 0.6.0 py_1
        - keepalive 0.5 py_1
        - libffi 3.2.1 hf484d3e_1005
        - libgcc-ng 7.3.0 hdf63c60_0
        - libiconv 1.15 h14c3975_1004
        - libstdcxx-ng 7.3.0 hdf63c60_0
        - libxml2 2.9.8 h143f9aa_1005
        - libxslt 1.1.32 h4785a14_1002
        - lockfile 0.12.2 py_1
        - lxml 4.3.1 py27h23eabaa_0
        - mistune 0.8.4 py27h14c3975_1000
        - msgpack-python 0.6.1 py27h6bb024c_0
        - mypy_extensions 0.4.1 py27_1000
        - ncurses 6.1 hf484d3e_1002
        - networkx 2.2 py_1
        - openssl 1.0.2p h14c3975_1002
        - pathlib2 2.3.2 py27_1000
        - pip 19.0.2 py27_0
        - prov 1.5.1 py_1
        - psutil 5.5.0 py27h14c3975_0
        - pycparser 2.19 py_0
        - pydotplus 2.0.2 py_1
        - pyopenssl 19.0.0 py27_0
        - pyparsing 2.3.1 py_0
        - pysocks 1.6.8 py27_1002
        - python 2.7.15 h938d71a_1006
        - python-dateutil 2.8.0 py_0
        - rdflib 4.2.2 py27_1000
        - rdflib-jsonld 0.4.0 py27_1000
        - readline 7.0 hf8c457e_1001
        - requests 2.21.0 py27_1000
        - ruamel.ordereddict 0.4.13 py27h14c3975_0
        - ruamel.yaml 0.15.77 py27h470a237_0
        - scandir 1.9.0 py27h14c3975_1000
        - schema-salad 3.0.20181206233650 py27_1000
        - setuptools 40.8.0 py27_0
        - shellescape 3.4.1 py_0
        - six 1.12.0 py27_1000
        - sparqlwrapper 1.8.2 py27_1000
        - sqlite 3.26.0 h67949de_1000
        - subprocess32 3.5.3 py27h14c3975_0
        - tk 8.6.9 h84994c4_1000
        - typing 3.6.6 py27_1000
        - typing_extensions 3.6.6 py27_1000
        - urllib3 1.24.1 py27_1000
        - webencodings 0.5.1 py_1
        - wheel 0.33.0 py27_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - cwltool
        - python
test:
    commands:
        - cwl-runner --help
about:
    home: https://github.com/common-workflow-language/common-workflow-language
    license: Apache 2.0
    license_family: APACHE
    license_file: /home/conda/recipe_root/LICENSE.txt
    summary: This provides an alternate entry point to cwltool allowing cwl-runner
        to be used as an implementation-agnostic script interpreter.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - npavlovikj
