# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Sep 29 10:38:04 2020
# ------------------------------------------------

package:
    name: jupyterlab_pygments
    version: 0.1.2
source:
    sha256: cfcda0873626150932f438eccf0f8bf22bfa92345b814890ab360d666b254146
    url: https://pypi.io/packages/source/j/jupyterlab_pygments/jupyterlab_pygments-0.1.2.tar.gz
build:
    noarch: python
    number: '0'
    script: /home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: pyh9f0ad1d_0
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9f0ad1d_0
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h24d8f2e_16
        - libgomp 9.3.0 h24d8f2e_16
        - libstdcxx-ng 9.3.0 hdf63c60_16
        - ncurses 6.2 he1b5a44_1
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.6.11 h4d41432_2_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py36h9f0ad1d_1
        - sqlite 3.33.0 h4cf870e_0
        - tk 8.6.10 hed695b0_0
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - pygments >=2.4.1,<3
        - python
test:
    imports:
        - jupyterlab_pygments
about:
    description: 'The goal is to enable the use of JupyterLab''s themes with pygments-generated
        HTML.

        '
    dev_url: https://github.com/JupyterLab/jupyterlab_pygments
    home: http://github.com/JupyterLab/jupyterlab_pygments
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Pygments syntax coloring scheme making use of the JupyterLab CSS variables
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - maartenbreddels
