# This file created by conda-build 3.20.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun Oct 11 06:01:31 2020
# ------------------------------------------------

package:
    name: gobject-introspection
    version: 1.66.1
source:
    patches:
        - test-fix.patch
    sha256: dd44a55ee5f426ea22b6b89624708f9e8d53f5cc94e5485c15c87cb30e06161d
    url: https://download.gnome.org/sources/gobject-introspection/1.66/gobject-introspection-1.66.1.tar.xz
build:
    number: '1'
    string: py37h619baee_1
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35 h18a2f87_9
        - binutils_linux-64 2.35 hc3fd857_29
        - bison 3.4 he1b5a44_1
        - flex 2.6.4 he1b5a44_1004
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 he2a3fca_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35 h769bd43_9
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - m4 1.4.18 h516909a_1001
        - ninja 1.10.1 hc9558a2_1
        - patch 2.7.6 h14c3975_1001
        - pkg-config 0.29.2 h516909a_1006
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - cairo 1.16.0 h3fc0475_1005
        - certifi 2020.6.20 py37he5f6b98_2
        - fontconfig 2.13.1 h1056068_1002
        - freetype 2.10.3 he06d7ca_0
        - gettext 0.19.8.1 hc5be6a0_1002
        - glib 2.58.3 py37he00f558_1004
        - icu 67.1 he1b5a44_0
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libiconv 1.16 h516909a_0
        - libpng 1.6.37 hed695b0_2
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.10 h68273f3_2
        - meson 0.55.3 py_0
        - ncurses 6.2 he1b5a44_1
        - ninja 1.10.1 hc9558a2_1
        - openssl 1.1.1h h516909a_0
        - pcre 8.44 he1b5a44_0
        - pixman 0.38.0 h516909a_1003
        - pthread-stubs 0.4 h14c3975_1001
        - python 3.7.8 h6f2ec95_1_cpython
        - python_abi 3.7 1_cp37m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py37he5f6b98_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.10 h516909a_0
        - xorg-libsm 1.2.3 h84519dc_1000
        - xorg-libx11 1.6.12 h516909a_0
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-libxext 1.3.4 h516909a_0
        - xorg-libxrender 0.9.10 h516909a_1002
        - xorg-renderproto 0.11.1 h14c3975_1002
        - xorg-xextproto 7.3.0 h14c3975_1002
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1009
    run:
        - cairo >=1.16.0,<1.17.0a0
        - glib >=2.58.3,<3.0a0
        - libffi >=3.2.1,<3.3.0a0
        - libffi >=3.2.1,<3.3.0a0
        - libgcc-ng >=7.5.0
        - python >=3.7,<3.8.0a0
        - python_abi 3.7.* *_cp37m
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
        - g-ir-scanner --help
        - g-ir-compiler --help
        - test -f `pkg-config --variable=g_ir_scanner --dont-define-prefix gobject-introspection-1.0`
    downstreams:
        - pygobject
    requires:
        - pkg-config
about:
    home: https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
    license: LGPL-2.0-or-later
    license_family: LGPL
    license_file: COPYING
    summary: Middleware for binding GObject-based code to other languages.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - ocefpaf
        - pkgw
        - scopatz
        - tschoonj
