# This file created by conda-build 3.18.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jun 18 01:04:58 2019
# ------------------------------------------------

package:
    name: xorg-libxt
    version: 1.1.5
source:
    fn: xorg-libXt-1.1.5.tar.bz2
    sha256: 46eeb6be780211fdd98c5109286618f6707712235fdd19df4ce1e6954f349f1a
    url: https://www.x.org/releases/individual/lib/libXt-1.1.5.tar.bz2
build:
    detect_binary_files_with_prefix: true
    number: '1003'
    string: h516909a_1003
requirements:
    build:
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - make 4.2.1 h14c3975_2004
        - pkg-config 0.29.2 h14c3975_1005
    host:
        - libgcc-ng 9.1.0 hdf63c60_0
        - libuuid 2.32.1 h14c3975_1000
        - libxcb 1.13 h14c3975_1002
        - pthread-stubs 0.4 h14c3975_1001
        - xorg-kbproto 1.0.7 h14c3975_1002
        - xorg-libice 1.0.9 h516909a_1004
        - xorg-libsm 1.2.3 h84519dc_1000
        - xorg-libx11 1.6.7 h14c3975_1000
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-util-macros 1.19.2 h14c3975_1001
        - xorg-xproto 7.0.31 h14c3975_1007
    run:
        - libgcc-ng >=7.3.0
        - xorg-kbproto
        - xorg-libice 1.0.*
        - xorg-libsm 1.2.*
        - xorg-libx11 1.6.*
        - xorg-xproto
test:
    commands:
        - test -f $PREFIX/lib/libXt.so
        - conda inspect linkages -p $PREFIX $PKG_NAME
about:
    home: https://www.x.org/
    license: MIT
    license_family: MIT
    license_file: COPYING
    summary: The X.org X11 toolkit intrinsics library.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pkgw
